import type { LaunchLocale } from './config'

const copy = {
  en: {
    mapLabel: 'Interactive student city map', loading: 'Loading the map…', loadFailed: 'The map could not load. The city list is still available.', retry: 'Try again', zoomIn: 'Zoom in', zoomOut: 'Zoom out', showAll: 'Show all results', mapHelp: 'Drag to explore · use + / − to zoom', tileUnavailable: 'The basemap is unavailable. City markers and the list remain usable.',
    results: 'Cities on this map', selectCity: 'Select a city to explore', selectHint: 'Choose a pin or a city in the list to see universities and local information.', located: 'with catalogued coordinates', missing: 'Location not recorded', coverage: 'Pins show approximate city locations recorded in the catalogue. All cities remain in the list.', cityGuide: 'Explore city & universities', googleMaps: 'Open Google Maps', universities: 'Universities in the catalogue', cityCentre: 'Approximate city centre · campus locations may differ', clearSelection: 'Close city details', noCoordinates: 'This city has no coordinates in the catalogue. Use its guide or search Google Maps by name.',
  },
  zh: {
    mapLabel: '留学城市交互地图', loading: '地图加载中…', loadFailed: '地图暂时无法加载，你仍可使用城市列表。', retry: '重试', zoomIn: '放大地图', zoomOut: '缩小地图', showAll: '显示全部结果', mapHelp: '拖动浏览 · 使用 + / − 缩放', tileUnavailable: '底图暂时无法连接，城市标记和列表仍可使用。',
    results: '探索城市', selectCity: '选择一座城市，开始探索', selectHint: '点击地图标记或左侧城市，查看高校和城市详情。', located: '座已有目录坐标', missing: '位置尚未记录', coverage: '标记表示目录中记录的城市大致位置，所有城市均可在列表中查看。', cityGuide: '探索城市与高校', googleMaps: '在 Google Maps 中查看', universities: '目录中的高校', cityCentre: '城市中心大致位置 · 不代表具体校区', clearSelection: '关闭城市详情', noCoordinates: '目录尚未记录这座城市的坐标，可查看城市指南或在 Google Maps 中按名称搜索。',
  },
  ru: {
    mapLabel: 'Интерактивная карта студенческих городов', loading: 'Загрузка карты…', loadFailed: 'Карта недоступна. Список городов продолжает работать.', retry: 'Повторить', zoomIn: 'Приблизить', zoomOut: 'Отдалить', showAll: 'Все результаты', mapHelp: 'Перетаскивайте карту · масштаб + / −', tileUnavailable: 'Подложка недоступна. Метки и список работают.',
    results: 'Города на карте', selectCity: 'Выберите город', selectHint: 'Нажмите на метку или город в списке, чтобы узнать о вузах.', located: 'с координатами в каталоге', missing: 'Местоположение не записано', coverage: 'Метки показывают примерное расположение городов по данным каталога. Все города доступны в списке.', cityGuide: 'Город и университеты', googleMaps: 'Открыть Google Maps', universities: 'Вузы в каталоге', cityCentre: 'Примерный центр города · кампус может быть в другом месте', clearSelection: 'Закрыть сведения', noCoordinates: 'В каталоге нет координат этого города. Откройте гид или поиск по названию в Google Maps.',
  },
  de: {
    mapLabel: 'Interaktive Karte der Studienstädte', loading: 'Karte wird geladen…', loadFailed: 'Karte nicht verfügbar. Die Städteliste bleibt nutzbar.', retry: 'Erneut versuchen', zoomIn: 'Vergrößern', zoomOut: 'Verkleinern', showAll: 'Alle Ergebnisse', mapHelp: 'Ziehen zum Erkunden · Zoom mit + / −', tileUnavailable: 'Basiskarte nicht verfügbar. Markierungen und Liste bleiben nutzbar.',
    results: 'Städte auf der Karte', selectCity: 'Eine Stadt entdecken', selectHint: 'Wählen Sie eine Markierung oder Stadt für Hochschulen und weitere Informationen.', located: 'mit Koordinaten im Katalog', missing: 'Position nicht erfasst', coverage: 'Markierungen zeigen ungefähre Stadtpositionen aus dem Katalog. Alle Städte bleiben in der Liste.', cityGuide: 'Stadt und Hochschulen', googleMaps: 'In Google Maps öffnen', universities: 'Hochschulen im Katalog', cityCentre: 'Ungefähres Stadtzentrum · Campusstandorte können abweichen', clearSelection: 'Stadtdetails schließen', noCoordinates: 'Für diese Stadt sind keine Koordinaten im Katalog erfasst. Nutzen Sie den Stadtführer oder die Namenssuche in Google Maps.',
  },
  fr: {
    mapLabel: 'Carte interactive des villes étudiantes', loading: 'Chargement de la carte…', loadFailed: 'Carte indisponible. La liste des villes reste accessible.', retry: 'Réessayer', zoomIn: 'Zoom avant', zoomOut: 'Zoom arrière', showAll: 'Tous les résultats', mapHelp: 'Glissez pour explorer · zoom + / −', tileUnavailable: 'Fond de carte indisponible. Les repères et la liste restent accessibles.',
    results: 'Villes sur la carte', selectCity: 'Choisissez une ville', selectHint: 'Sélectionnez un repère ou une ville pour découvrir ses universités.', located: 'avec coordonnées au catalogue', missing: 'Position non renseignée', coverage: 'Les repères indiquent les positions approximatives inscrites au catalogue. Toutes les villes restent dans la liste.', cityGuide: 'Ville et universités', googleMaps: 'Ouvrir Google Maps', universities: 'Universités du catalogue', cityCentre: 'Centre-ville approximatif · les campus peuvent être ailleurs', clearSelection: 'Fermer les détails', noCoordinates: 'Le catalogue ne contient pas de coordonnées pour cette ville. Consultez le guide ou cherchez son nom dans Google Maps.',
  },
  es: {
    mapLabel: 'Mapa interactivo de ciudades universitarias', loading: 'Cargando mapa…', loadFailed: 'El mapa no está disponible. La lista sigue funcionando.', retry: 'Reintentar', zoomIn: 'Acercar', zoomOut: 'Alejar', showAll: 'Todos los resultados', mapHelp: 'Arrastra para explorar · zoom + / −', tileUnavailable: 'El mapa base no está disponible. Los marcadores y la lista siguen funcionando.',
    results: 'Ciudades en el mapa', selectCity: 'Elige una ciudad', selectHint: 'Selecciona un marcador o una ciudad para descubrir sus universidades.', located: 'con coordenadas en el catálogo', missing: 'Ubicación no registrada', coverage: 'Los marcadores muestran ubicaciones aproximadas registradas en el catálogo. Todas las ciudades siguen en la lista.', cityGuide: 'Ciudad y universidades', googleMaps: 'Abrir Google Maps', universities: 'Universidades del catálogo', cityCentre: 'Centro aproximado de la ciudad · los campus pueden estar en otro lugar', clearSelection: 'Cerrar detalles', noCoordinates: 'El catálogo no contiene coordenadas de esta ciudad. Consulta la guía o busca el nombre en Google Maps.',
  },
} satisfies Record<LaunchLocale, Record<string, string>>

export function getCityMapCopy(locale: LaunchLocale) { return copy[locale] }

const privacy = {
  en: { title: 'Interactive maps', paragraphs: ['Map view loads image tiles directly from OpenStreetMap. Its servers receive normal connection details, including your IP address and this website’s origin. City search and filtering stay in your browser; we do not request your precise location. Google Maps opens only when you follow its link, under Google’s own policies.'] },
  zh: { title: '交互地图', paragraphs: ['地图视图会直接从 OpenStreetMap 加载底图，其服务器会收到 IP 地址和本站来源等常规连接信息。城市搜索与筛选在浏览器内完成；本站不会请求你的精确位置。只有点击相应链接才会打开 Google Maps，届时适用该服务自身的政策。'] },
  ru: { title: 'Интерактивные карты', paragraphs: ['Карта загружает изображения напрямую из OpenStreetMap. Сервис получает обычные данные соединения, включая IP-адрес и адрес этого сайта. Поиск и фильтры работают в браузере; точное местоположение не запрашивается. Google Maps открывается только по вашей ссылке и регулируется правилами Google.'] },
  de: { title: 'Interaktive Karten', paragraphs: ['Die Kartenansicht lädt Bildkacheln direkt von OpenStreetMap. Dabei erhält der Dienst übliche Verbindungsdaten wie Ihre IP-Adresse und die Herkunftsseite. Suche und Filter bleiben im Browser; Ihr genauer Standort wird nicht angefordert. Google Maps wird erst über den entsprechenden Link geöffnet und unterliegt den Richtlinien von Google.'] },
  fr: { title: 'Cartes interactives', paragraphs: ['La carte charge des images directement depuis OpenStreetMap, qui reçoit les données de connexion habituelles, dont votre adresse IP et l’origine de ce site. La recherche et les filtres restent dans le navigateur ; votre position précise n’est pas demandée. Google Maps ne s’ouvre que via son lien et applique ses propres politiques.'] },
  es: { title: 'Mapas interactivos', paragraphs: ['El mapa carga imágenes directamente de OpenStreetMap, que recibe los datos habituales de conexión, incluida tu dirección IP y el origen de este sitio. La búsqueda y los filtros funcionan en tu navegador; no solicitamos tu ubicación precisa. Google Maps solo se abre al pulsar su enlace y se rige por sus propias políticas.'] },
}

export function getCityMapPrivacy(locale: LaunchLocale) { return privacy[locale] }
