import type { LaunchLocale } from './config'

export type PolicySection = {
  title: string
  paragraphs?: string[]
  items?: string[]
}

const en = {
  brand: 'Study in China Atlas',
  shell: { brandTagline: 'Independent student atlas', navLabel: 'Primary navigation', mobileMenuLabel: 'Open menu', skipLinkLabel: 'Skip to main content', footerExplore: 'Explore', footerProject: 'Project', dataRelease: 'Data release', creatorPrefix: 'Created by' },
  nav: { home: 'Home', universities: 'Universities', programs: 'Programs', scholarships: 'Scholarships', cities: 'Cities', guides: 'Guides', favorites: 'Saved', about: 'About', contact: 'Contact' },
  common: { explore: 'Explore', viewDetails: 'View details', applyOfficial: 'Apply on official site', officialSource: 'Official source', verified: 'Verified', stale: 'Needs review', draft: 'Being verified', archived: 'Archived', lastVerified: 'Verified on', unknown: 'Not announced', all: 'All', search: 'Search', clear: 'Clear filters', save: 'Save', saved: 'Saved', compare: 'Compare', print: 'Print / Save PDF', back: 'Back', university: 'University', program: 'Program', scholarship: 'Scholarship', city: 'City', status: 'Status', openNow: 'Open now', deadline: 'Deadline', tuition: 'Tuition', duration: 'Duration', months: 'months', language: 'Teaching language', requirements: 'Language requirements', translationPending: 'Translation pending', authoritativeNotice: 'Admissions information changes. Always confirm on the linked official page.' },
  home: { eyebrow: 'A clearer path to studying in China', title: 'Compare programs. Track deadlines. Choose with confidence.', intro: 'A source-backed guide for international students exploring Chinese universities, scholarships, application routes and student cities.', findUniversity: 'Find a university', explorePrograms: 'Explore programs', checkScholarships: 'Check scholarships', learnCities: 'Learn about cities', featured: 'Start with trusted essentials', featuredIntro: 'Browse a carefully structured first release, with visible sources and review dates.', deadlineTitle: 'Application windows to watch', disciplines: 'Explore by field', cityTitle: 'Twelve student cities, one connected journey', guideTitle: 'Your application, step by step', programVerificationNote: 'Program records are being verified one by one. Drafts without an official program page are not published or indexed.', sourceHeading: 'Every fact should lead back to a source' },
  universities: { title: 'Universities', intro: 'Filter a curated national selection by city, region and academic field.', searchPlaceholder: 'Search university, city or field', noResults: 'No universities match these filters.', cityFilter: 'City', regionFilter: 'Region', fieldFilter: 'Field', results: 'universities', programs: 'Programs to explore', funding: 'Related scholarships', facts: 'University at a glance', sources: 'Sources and review', review: 'Review due', official: 'University website', admission: 'International admissions' },
  programs: { title: 'Programs', intro: 'Compare degree level, teaching language, duration and current admissions status.', searchPlaceholder: 'Search program or university', noResults: 'No programs match these filters.', degree: 'Degree level', discipline: 'Field', languageFilter: 'Teaching language', statusFilter: 'Application dates', tuitionFilter: 'Tuition data', published: 'Published', unannounced: 'Not announced', known: 'Available', results: 'programs', verificationNote: 'The public catalogue only accepts verified records with a program-level official source. Draft templates are excluded from production pages, the sitemap and structured data.', overview: 'Program facts', cycle: 'Admissions cycle', year: 'Academic year', intake: 'Intake', fee: 'Application fee', opens: 'Opens', sources: 'Official sources and review', related: 'Other programs at this university', university: 'University', faculty: 'Faculty', qualification: 'Qualification', studyMode: 'Study mode', languagePolicy: 'Language policy', curriculum: 'Curriculum highlights', eligibility: 'Eligibility', materials: 'Application materials', campus: 'Campus', fullTime: 'Full-time', partTime: 'Part-time', hybrid: 'Hybrid', applicationStatus: 'Application status', datePublished: 'Dates published', rolling: 'Rolling admissions', notAnnounced: 'Not announced', previousCycle: 'Previous-cycle reference', applicationsClosed: 'Applications closed', upcoming: 'Opening soon', springIntake: 'Spring intake', autumnIntake: 'Autumn intake', otherIntake: 'Other intake', tuitionProgram: 'per program', tuitionSemester: 'per semester', tuitionAcademicYear: 'per academic year', tuitionMonth: 'per month', tuitionOther: 'See official details' },
  scholarships: { title: 'Scholarships', intro: 'Understand coverage, eligibility routes and official application links.', coverage: 'Coverage', stipend: 'Monthly stipend', catalogueNotice: 'The public catalogue only shows scholarships verified against official sources; a listing does not necessarily mean applications are open.', tuition: 'Tuition', accommodation: 'Accommodation', insurance: 'Medical insurance', scope: 'Participating universities', sources: 'Sources and review', included: 'Included', notIncluded: 'Not included' },
  cities: { title: 'Student cities', intro: 'See where universities are located and get a concise feel for climate, food and everyday life.', climate: 'Climate at a glance', food: 'What to taste', sights: 'What to see', universities: 'Universities in this city', mapNote: 'This is a latitude/longitude city index, not a map, and it does not depict boundaries. A reviewed standard map will be added after compliant assets and authorization are secured.', plotNote: 'City markers are approximate and informational.', officialMapService: 'View the Ministry of Natural Resources standard map service', contentTitle: 'About city content', contentNotice: 'Climate, food and sights are a concise orientation, not travel or safety advice.' },
  favorites: { title: 'Your shortlist', intro: 'Saved on this device. Select up to four programs for a compact comparison.', empty: 'You have not saved any programs yet.', localOnly: 'Saved items stay in this browser and are not uploaded.', loading: 'Loading this device’s shortlist…', choose: 'Select for comparison', limit: 'Choose up to four programs.', comparison: 'Program comparison', remove: 'Remove', university: 'University' },
  guide: { title: 'Application guides', intro: 'Practical, source-conscious checklists from shortlisting to arrival.', eyebrow: 'Applicant pathway', usingTitle: 'When using this guide', disclaimer: 'This guide does not replace requirements issued by a university, scholarship body, consulate or immigration authority.' },
  about: { title: 'A public-interest guide built around evidence', intro: 'Study in China Atlas organizes scattered official information into a more transparent starting point.', mission: 'Why this exists', missionText: 'International applicants often compare dozens of pages with different formats and update cycles. This project makes the comparison clearer while keeping the official source one click away.', creator: 'About the creator', creatorText: 'Created and maintained by Henry Yang as a non-commercial information project for international students.', data: 'How data is maintained', dataText: 'Facts are stored in version-controlled files, reviewed against official sources, and automatically checked for staleness and broken links.', creatorWebsite: 'Creator website', principlesTitle: 'Open, traceable and non-commercial', versionedChanges: 'Versioned fact changes', sourceLinkedFacts: 'Facts linked to official sources', publicLanguages: 'Public interface languages', noAds: 'Ads or affiliate links' },
  contact: { title: 'Contact and corrections', intro: 'Report outdated information, a broken link, or suggest a program. Please do not send application documents.', category: 'What is this about?', incorrect: 'Incorrect or outdated data', broken: 'Broken link', suggest: 'Suggest a program', other: 'Other', message: 'Your message', source: 'Official source link (optional)', email: 'Reply email (optional)', consent: 'I understand this form is only for feedback and I will not submit sensitive application documents.', submit: 'Send feedback', sending: 'Sending…', success: 'Thank you. Your feedback was sent privately.', error: 'The message could not be sent. Please try again later.', configurationNote: 'The private form becomes available after Turnstile, Resend and rate-limit variables are configured.', privacyTitle: 'Privacy first', sensitiveNotice: 'Do not submit passports, transcripts, health data, recommendation letters, admission documents or payment information. The creator’s private email is not exposed.', sourceSuggestion: 'Adding an official source link helps us verify a correction faster.', creatorWebsite: 'Visit creator website' },
  notFound: { title: 'Page not found', description: 'The link may have changed, or this record has not been published.', action: 'Back to home' },
  updates: { eyebrow: 'Changelog', title: 'Updates', description: 'A public record of meaningful product, data and policy changes.', badge: 'Data release', releaseTitle: 'Six-language platform release', items: ['Published English, Chinese, Russian, German, French and Spanish routes.', 'Added structured university, program, city and scholarship data with source and review metadata.', 'Added favorites, comparison, secure feedback, multilingual SEO and automated data-health checks.'] },
  legal: {
    privacy: { eyebrow: 'Last updated: 16 July 2026', title: 'Privacy policy', intro: 'This site minimizes data collection, creates no user accounts and stores no application documents.', sections: [
      { title: 'Local storage', paragraphs: ['Favorites and comparison selections stay in your browser and are never uploaded. Clearing browser data removes them.'] },
      { title: 'Feedback form', paragraphs: ['Your message, optional reply email, page and source link are privately sent to the creator through Resend. No feedback database is created.'], items: ['Do not submit passports, transcripts, health records, recommendations, payment data or other application files.', 'IP addresses are HMAC-hashed only for a five-per-hour limit; the rate-limit key expires after one hour.'] },
      { title: 'Analytics and processors', paragraphs: ['Vercel Web Analytics and Speed Insights measure aggregate performance without advertising trackers. Turnstile prevents bots and Resend delivers feedback.'] },
      { title: 'Contact and deletion', paragraphs: ['To ask about or delete feedback you sent, use the contact form and provide enough information to identify it.'] },
    ] as PolicySection[] },
    disclaimer: { eyebrow: 'Important notice', title: 'Disclaimer', intro: 'This is an independent, non-commercial information project. It does not represent any university, government or scholarship body.', sections: [
      { title: 'Official information takes priority', paragraphs: ['Cycles, fees, language requirements, scholarships and visa rules change. Reconfirm them on the linked official source before applying, paying or travelling.'] },
      { title: 'No admission or funding guarantee', paragraphs: ['Listing a university, program or scholarship is not an endorsement and does not guarantee eligibility, admission, a visa or funding.'] },
      { title: 'External links', paragraphs: ['External sites are controlled by their operators. This project cannot control their content, availability or privacy practices.'] },
    ] as PolicySection[] },
    dataPolicy: { eyebrow: 'Source-led methodology', title: 'Data sources and update policy', intro: 'Every changing admissions fact should have a source, verification date, review date and visible status.', sections: [
      { title: 'Source hierarchy', items: ['Prefer university international-admissions pages, official application systems and government pages.', 'Social media, reposts and third-party platforms are leads only; they cannot alone support fees, deadlines or requirements.'] },
      { title: 'Status meanings', items: ['Verified: checked against a current official source and eligible for publication.', 'Being verified: not publication-reviewed and excluded from production pages and search engines.', 'Needs review: past its review date or conflicting; it remains visibly marked.', 'Archived: retained in versioned data history, not published as current guidance.'] },
      { title: 'Unknown and previous cycles', paragraphs: ['Unannounced values are stored as null and shown as not announced. Previous cycles are archived, never copied into a current year.'] },
      { title: 'Review cadence', items: ['Links are checked weekly; 403, 429 and timeouts become manual-review items.', 'A monthly data-health issue is created; full manual reviews happen in January and August–September.', 'Automation creates tasks but never publishes admissions facts automatically.'] },
    ] as PolicySection[] },
  },
  footer: { project: 'An independent, non-commercial guide. Official university notices always take priority.', creator: 'Created by Henry Yang', privacy: 'Privacy', disclaimer: 'Disclaimer', dataPolicy: 'Data policy', updates: 'Updates' },
}

type BaseMessages = typeof en
type ProgramExtraMessages = {
  viewApplicationPortal: string
  tuitionReference: string
  evidenceBasis: string
  cycleSpecific: string
  recurringRule: string
}

export type Messages = Omit<BaseMessages, 'programs'> & {
  programs: BaseMessages['programs'] & ProgramExtraMessages
}

const zh: BaseMessages = {
  brand: '中国留学指南',
  shell: { brandTagline: '独立留学资料地图', navLabel: '主导航', mobileMenuLabel: '打开菜单', skipLinkLabel: '跳到主要内容', footerExplore: '探索', footerProject: '项目', dataRelease: '数据版本', creatorPrefix: '创作者：' },
  nav: { home: '首页', universities: '大学', programs: '项目', scholarships: '奖学金', cities: '城市', guides: '申请指南', favorites: '收藏', about: '关于', contact: '联系' },
  common: { explore: '开始探索', viewDetails: '查看详情', applyOfficial: '前往官网申请', officialSource: '官方来源', verified: '已核验', stale: '需要复核', draft: '核验中', archived: '已归档', lastVerified: '核验日期', unknown: '尚未公布', all: '全部', search: '搜索', clear: '清除筛选', save: '收藏', saved: '已收藏', compare: '对比', print: '打印 / 另存为 PDF', back: '返回', university: '大学', program: '项目', scholarship: '奖学金', city: '城市', status: '状态', openNow: '开放申请', deadline: '截止日期', tuition: '学费', duration: '学制', months: '个月', language: '授课语言', requirements: '语言要求', translationPending: '翻译待补充', authoritativeNotice: '招生信息可能变化，请始终以所链接的学校官方公告为准。' },
  home: { eyebrow: '更清晰的中国留学路径', title: '比较项目，掌握时间，安心选择。', intro: '为国际学生整理中国高校、奖学金、申请路径与留学城市信息，并为关键事实标注来源。', findUniversity: '寻找大学', explorePrograms: '浏览项目', checkScholarships: '查看奖学金', learnCities: '了解城市', featured: '从可信的核心信息开始', featuredIntro: '浏览结构化的首批资料，每条信息均显示来源与核验时间。', deadlineTitle: '值得关注的申请窗口', disciplines: '按学科探索', cityTitle: '十二座留学城市，一段中国旅程', guideTitle: '申请流程，一步一步完成', programVerificationNote: '项目资料正在逐项核验。未经官方项目页确认的草稿不会出现在公开目录或搜索引擎中。', sourceHeading: '每条事实都应能回到来源' },
  universities: { title: '中国大学', intro: '按城市、地区和学科筛选精选高校。', searchPlaceholder: '搜索学校、城市或学科', noResults: '没有符合当前条件的大学。', cityFilter: '城市', regionFilter: '地区', fieldFilter: '学科', results: '所大学', programs: '可浏览项目', funding: '相关奖学金', facts: '学校概览', sources: '来源与复核', review: '下次复核', official: '大学官网', admission: '国际招生官网' },
  programs: { title: '学习项目', intro: '比较学位、授课语言、学制和当前申请状态。', searchPlaceholder: '搜索项目或大学', noResults: '没有符合当前条件的项目。', degree: '学位类型', discipline: '学科领域', languageFilter: '授课语言', statusFilter: '申请日期', tuitionFilter: '学费信息', published: '已公布', unannounced: '尚未公布', known: '已有数据', results: '个项目', verificationNote: '公开目录目前只接受有项目级官方来源的核验记录。模板草稿已从生产页面、站点地图和结构化数据中隔离。', overview: '项目信息', cycle: '招生周期', year: '适用学年', intake: '入学季', fee: '申请费', opens: '开放日期', sources: '官方来源与核验', related: '同校其他项目', university: '开设学校', faculty: '院系', qualification: '授予资格', studyMode: '学习方式', languagePolicy: '语言政策', curriculum: '课程亮点', eligibility: '申请资格', materials: '申请材料', campus: '校区', fullTime: '全日制', partTime: '非全日制', hybrid: '混合制', applicationStatus: '申请状态', datePublished: '日期已公布', rolling: '滚动录取', notAnnounced: '尚未公布', previousCycle: '上一周期参考', applicationsClosed: '申请已截止', upcoming: '即将开放', springIntake: '春季入学', autumnIntake: '秋季入学', otherIntake: '其他入学季', tuitionProgram: '每个项目', tuitionSemester: '每学期', tuitionAcademicYear: '每学年', tuitionMonth: '每月', tuitionOther: '见官方说明' },
  scholarships: { title: '奖学金', intro: '了解资助范围、申请渠道和官方申请链接。', coverage: '资助范围', stipend: '每月生活费', catalogueNotice: '公开目录只显示已经过官方来源核验的奖学金；列出名称并不代表当期一定开放。', tuition: '学费', accommodation: '住宿', insurance: '医疗保险', scope: '适用学校', sources: '来源与核验', included: '包含', notIncluded: '不包含' },
  cities: { title: '留学城市', intro: '查看大学分布，并快速了解气候、美食与城市生活。', climate: '气候概览', food: '当地美食', sights: '城市风景', universities: '本市大学', mapNote: '当前展示的是经纬度城市索引，并非地图，也不表示任何边界。取得合规资产与授权后，将上线经审图的标准地图。', plotNote: '城市标记位置为近似位置，仅供信息参考。', officialMapService: '查看自然资源部标准地图服务', contentTitle: '城市资料说明', contentNotice: '气候、美食与景点为简要生活参考，不构成旅行或安全建议。' },
  favorites: { title: '我的收藏', intro: '收藏保存在当前设备，可选择最多四个项目进行对比。', empty: '你还没有收藏任何项目。', localOnly: '收藏只保存在本浏览器，不会上传。', loading: '正在读取本机收藏…', choose: '选择用于对比', limit: '最多选择四个项目。', comparison: '项目对比', remove: '移出收藏', university: '学校' },
  guide: { title: '申请指南', intro: '从选校到入境的实用、可核验清单。', eyebrow: '申请路径', usingTitle: '使用本指南时', disclaimer: '本指南不替代大学、奖学金机构、使领馆或移民管理部门的正式要求。' },
  about: { title: '以证据为基础的公益留学指南', intro: '中国留学指南把分散的官方信息整理成透明、清晰的起点。', mission: '为什么创建这个网站', missionText: '国际申请者往往需要比较格式和更新时间各不相同的众多页面。本项目让比较更清楚，同时始终保留直达官方来源的链接。', creator: '关于创作者', creatorText: '由 Henry Yang 创建并维护，是一个面向国际学生的非商业信息项目。', data: '数据如何维护', dataText: '事实信息保存在可追踪版本的文件中，通过官方来源人工核验，并自动检查过期时间与失效链接。', creatorWebsite: '创作者主页', principlesTitle: '开放、可追踪、非商业', versionedChanges: '所有事实变更保留历史', sourceLinkedFacts: '动态事实关联官方来源', publicLanguages: '公开界面语言', noAds: '广告与联盟链接' },
  contact: { title: '联系与纠错', intro: '报告过期信息、失效链接或推荐项目。请不要发送申请文件。', category: '反馈类型', incorrect: '错误或过期信息', broken: '失效链接', suggest: '推荐项目', other: '其他', message: '反馈内容', source: '官方来源链接（可选）', email: '回复邮箱（可选）', consent: '我了解此表单仅用于反馈，并且不会提交任何敏感申请文件。', submit: '发送反馈', sending: '发送中…', success: '谢谢，反馈已私密发送。', error: '暂时无法发送，请稍后重试。', configurationNote: '部署者配置 Turnstile、Resend 和限流环境变量后，私密反馈表单即可启用。', privacyTitle: '隐私优先', sensitiveNotice: '请勿提交护照、成绩单、健康资料、推荐信、录取文件或付款信息。作者的私人邮箱不会在网页公开，反馈将通过服务端私密转发。', sourceSuggestion: '建议附上官方来源链接，帮助我们更快核验。', creatorWebsite: '访问创作者主页' },
  notFound: { title: '没有找到这个页面', description: '链接可能已更改，或该资料尚未发布。', action: '返回首页' },
  updates: { eyebrow: '更新日志', title: '更新记录', description: '公开记录产品、数据与政策的主要变化。', badge: '数据版本', releaseTitle: '六语平台版本上线', items: ['发布英语、中文、俄语、德语、法语和西班牙语路由。', '加入带来源与复核元数据的结构化大学、项目、城市和奖学金资料。', '加入收藏、对比、私密反馈、多语言 SEO 与自动数据健康检查。'] },
  legal: {
    privacy: { eyebrow: '最后更新：2026-07-16', title: '隐私政策', intro: '本网站尽量少收集数据，不建立用户账号，也不存储留学申请材料。', sections: [
      { title: '本地保存', paragraphs: ['收藏与对比清单只保存在你的浏览器中，不会上传到本站。清除浏览器数据会删除这些内容。'] },
      { title: '反馈表单', paragraphs: ['提交反馈时，消息、可选回复邮箱、相关页面和来源链接会通过 Resend 私密发送给作者，不建立反馈数据库。'], items: ['请勿提交护照、成绩单、健康资料、推荐信、付款资料或其他申请文件。', 'IP 地址经 HMAC 处理后仅用于一小时五次的限流；限流键在一小时后过期。'] },
      { title: '分析与第三方', paragraphs: ['本站使用 Vercel Web Analytics 和 Speed Insights 了解总体性能，不加入广告跟踪。Turnstile 用于防机器人，Resend 用于邮件转发。'] },
      { title: '联系与删除', paragraphs: ['如需查询或删除你发送的反馈，请通过联系表单提供可识别该消息的信息。'] },
    ] },
    disclaimer: { eyebrow: '重要说明', title: '免责声明', intro: '本站是独立、非商业的资料整理项目，不代表任何大学、政府机构或奖学金机构。', sections: [
      { title: '官方信息优先', paragraphs: ['招生周期、费用、语言要求、奖学金和签证政策会变化。申请、付款或旅行安排前，必须在所链接的官方页面重新确认。'] },
      { title: '不保证录取或资助', paragraphs: ['收录某个学校、项目或奖学金不构成推荐，也不保证资格、录取、签证或资助。'] },
      { title: '外部链接', paragraphs: ['外部网站由其运营方负责。本站会检查链接，但无法控制其内容、可用性或隐私做法。'] },
    ] },
    dataPolicy: { eyebrow: '可信资料方法', title: '数据来源与更新政策', intro: '每条动态招生事实都应有来源、核验日期、复核日期和可见状态。', sections: [
      { title: '来源优先级', items: ['优先使用大学国际招生官网、官方申请系统和政府机构页面。', '社交媒体、转载和第三方平台只用于发现线索，不能单独支持费用、截止日期或要求。'] },
      { title: '状态含义', items: ['已核验：已根据当前官方来源核对，可进入公开目录。', '核验中：已录入但尚未完成发布级复核，不会进入生产页面或搜索引擎。', '需要复核：已超过计划复核日期或存在冲突，可继续显示但会醒目标记。', '已归档：历史记录仅保留在版本数据中，不作为当前申请依据。'] },
      { title: '未知与旧周期', paragraphs: ['未公布字段保存为 null 并显示“尚未公布”。旧周期归档，不复制为当前日期。'] },
      { title: '更新节奏', items: ['每周自动检查外链；403、429 和超时转为人工检查。', '每月生成数据健康清单；每年 1 月与 8–9 月全量人工复核。', '自动化只创建待办，不自动发布招生事实。'] },
    ] },
  },
  footer: { project: '独立、非商业信息指南；请始终以大学官方公告为准。', creator: '创作者 Henry Yang', privacy: '隐私', disclaimer: '免责声明', dataPolicy: '数据政策', updates: '更新记录' },
}

const ru: BaseMessages = {
  brand: 'Атлас учёбы в Китае',
  shell: { brandTagline: 'Независимый атлас', navLabel: 'Основная навигация', mobileMenuLabel: 'Открыть меню', skipLinkLabel: 'К основному содержанию', footerExplore: 'Навигация', footerProject: 'Проект', dataRelease: 'Версия данных', creatorPrefix: 'Автор:' },
  nav: { home: 'Главная', universities: 'Вузы', programs: 'Программы', scholarships: 'Стипендии', cities: 'Города', guides: 'Поступление', favorites: 'Сохранённое', about: 'О проекте', contact: 'Связаться' },
  common: { explore: 'Открыть', viewDetails: 'Подробнее', applyOfficial: 'Подать на официальном сайте', officialSource: 'Официальный источник', verified: 'Проверено', stale: 'Нужна проверка', draft: 'Проверяется', archived: 'Архив', lastVerified: 'Проверено', unknown: 'Не объявлено', all: 'Все', search: 'Поиск', clear: 'Сбросить', save: 'Сохранить', saved: 'Сохранено', compare: 'Сравнить', print: 'Печать / PDF', back: 'Назад', university: 'Университет', program: 'Программа', scholarship: 'Стипендия', city: 'Город', status: 'Статус', openNow: 'Приём открыт', deadline: 'Срок подачи', tuition: 'Стоимость', duration: 'Длительность', months: 'месяцев', language: 'Язык обучения', requirements: 'Языковые требования', translationPending: 'Перевод готовится', authoritativeNotice: 'Условия поступления меняются. Всегда сверяйтесь с официальной страницей по ссылке.' },
  home: { eyebrow: 'Понятный путь к учёбе в Китае', title: 'Сравнивайте программы. Следите за сроками. Выбирайте уверенно.', intro: 'Путеводитель по китайским вузам, стипендиям, поступлению и студенческим городам с указанием источников.', findUniversity: 'Найти вуз', explorePrograms: 'Смотреть программы', checkScholarships: 'Найти стипендию', learnCities: 'Узнать о городах', featured: 'Начните с проверенной основы', featuredIntro: 'Первый структурированный набор данных с источниками и датами проверки.', deadlineTitle: 'Сроки, за которыми стоит следить', disciplines: 'Поиск по направлению', cityTitle: 'Двенадцать студенческих городов — одно путешествие', guideTitle: 'Поступление шаг за шагом', programVerificationNote: 'Программы проходят проверку. Черновики без официальной страницы программы не публикуются и не индексируются.', sourceHeading: 'Каждый факт ведёт к источнику' },
  universities: { title: 'Университеты', intro: 'Фильтруйте подборку по городу, региону и направлению.', searchPlaceholder: 'Поиск вуза, города или направления', noResults: 'По этим фильтрам ничего не найдено.', cityFilter: 'Город', regionFilter: 'Регион', fieldFilter: 'Направление', results: 'вузов', programs: 'Программы', funding: 'Стипендии', facts: 'О вузе', sources: 'Источники и проверка', review: 'Следующая проверка', official: 'Сайт вуза', admission: 'Приём иностранных студентов' },
  programs: { title: 'Программы', intro: 'Сравнивайте степень, язык, длительность и статус приёма.', searchPlaceholder: 'Поиск программы или вуза', noResults: 'Программы не найдены.', degree: 'Уровень', discipline: 'Направление', languageFilter: 'Язык', statusFilter: 'Сроки', tuitionFilter: 'Стоимость', published: 'Опубликованы', unannounced: 'Не объявлены', known: 'Есть данные', results: 'программ', verificationNote: 'В открытом каталоге публикуются только проверенные записи с официальным источником уровня программы. Черновики исключены из страниц, карты сайта и структурированных данных.', overview: 'О программе', cycle: 'Цикл приёма', year: 'Учебный год', intake: 'Набор', fee: 'Сбор', opens: 'Открытие', sources: 'Источники и проверка', related: 'Другие программы вуза', university: 'Университет', faculty: 'Факультет', qualification: 'Квалификация', studyMode: 'Форма обучения', languagePolicy: 'Языковая политика', curriculum: 'Основные дисциплины', eligibility: 'Требования к кандидатам', materials: 'Документы для подачи', campus: 'Кампус', fullTime: 'Очная форма', partTime: 'Неполная занятость', hybrid: 'Гибридная форма', applicationStatus: 'Статус подачи', datePublished: 'Даты опубликованы', rolling: 'Непрерывный приём', notAnnounced: 'Не объявлено', previousCycle: 'Данные прошлого цикла', applicationsClosed: 'Приём завершён', upcoming: 'Скоро откроется', springIntake: 'Весенний набор', autumnIntake: 'Осенний набор', otherIntake: 'Другой набор', tuitionProgram: 'за программу', tuitionSemester: 'за семестр', tuitionAcademicYear: 'за учебный год', tuitionMonth: 'в месяц', tuitionOther: 'См. официальные сведения' },
  scholarships: { title: 'Стипендии', intro: 'Покрытие, маршруты подачи и официальные ссылки.', coverage: 'Покрытие', stipend: 'Ежемесячная выплата', catalogueNotice: 'В открытом каталоге показаны только стипендии, проверенные по официальным источникам; наличие записи не означает открытый набор.', tuition: 'Обучение', accommodation: 'Проживание', insurance: 'Страховка', scope: 'Вузы', sources: 'Источники и проверка', included: 'Включено', notIncluded: 'Не включено' },
  cities: { title: 'Студенческие города', intro: 'Расположение вузов, климат, кухня и повседневная жизнь.', climate: 'Климат', food: 'Что попробовать', sights: 'Что увидеть', universities: 'Вузы города', mapNote: 'Сейчас показан индекс городов по координатам, а не карта; он не отображает границы. Проверенная стандартная карта появится после получения соответствующих материалов и разрешений.', plotNote: 'Положение меток приблизительное и носит справочный характер.', officialMapService: 'Открыть сервис стандартных карт Министерства природных ресурсов КНР', contentTitle: 'О городских данных', contentNotice: 'Климат, кухня и достопримечательности приведены как краткий ориентир, а не совет по поездке или безопасности.' },
  favorites: { title: 'Ваш список', intro: 'Сохранено на этом устройстве. Сравните до четырёх программ.', empty: 'Сохранённых программ пока нет.', localOnly: 'Данные остаются в браузере и не загружаются на сервер.', loading: 'Загрузка списка…', choose: 'Выбрать для сравнения', limit: 'Можно сравнить до четырёх программ.', comparison: 'Сравнение', remove: 'Удалить', university: 'Университет' },
  guide: { title: 'Гиды по поступлению', intro: 'Практические списки от выбора программы до приезда.', eyebrow: 'Путь абитуриента', usingTitle: 'Как использовать этот гид', disclaimer: 'Гид не заменяет официальные требования вуза, стипендиальной организации, консульства или миграционных органов.' },
  about: { title: 'Общественный проект, основанный на источниках', intro: 'Атлас собирает разрозненную официальную информацию в понятную отправную точку.', mission: 'Зачем создан проект', missionText: 'Абитуриентам приходится сравнивать десятки страниц разного формата и давности. Проект упрощает сравнение и сохраняет прямую ссылку на официальный источник.', creator: 'Об авторе', creatorText: 'Некоммерческий информационный проект для иностранных студентов, созданный и поддерживаемый Henry Yang.', data: 'Как обновляются данные', dataText: 'Факты хранятся в файлах с историей изменений, проверяются по официальным источникам и автоматически контролируются на устаревание и битые ссылки.', creatorWebsite: 'Сайт автора', principlesTitle: 'Открыто, отслеживаемо и некоммерчески', versionedChanges: 'История изменений фактов', sourceLinkedFacts: 'Факты связаны с источниками', publicLanguages: 'Языки интерфейса', noAds: 'Реклама и партнёрские ссылки' },
  contact: { title: 'Связь и исправления', intro: 'Сообщите об устаревших данных, битой ссылке или предложите программу. Не отправляйте документы.', category: 'Тема', incorrect: 'Ошибка или устаревшие данные', broken: 'Битая ссылка', suggest: 'Предложить программу', other: 'Другое', message: 'Сообщение', source: 'Официальная ссылка (необязательно)', email: 'Email для ответа (необязательно)', consent: 'Я понимаю, что форма предназначена только для обратной связи, и не буду отправлять конфиденциальные документы.', submit: 'Отправить', sending: 'Отправка…', success: 'Спасибо. Сообщение отправлено конфиденциально.', error: 'Не удалось отправить сообщение. Попробуйте позже.', configurationNote: 'Приватная форма станет доступна после настройки Turnstile, Resend и ограничения частоты.', privacyTitle: 'Конфиденциальность', sensitiveNotice: 'Не отправляйте паспорт, оценки, медицинские данные, рекомендации, документы о зачислении или платёжные данные. Личный адрес автора не публикуется.', sourceSuggestion: 'Добавьте официальную ссылку — это ускорит проверку.', creatorWebsite: 'Сайт автора' },
  notFound: { title: 'Страница не найдена', description: 'Ссылка могла измениться или материал ещё не опубликован.', action: 'На главную' },
  updates: { eyebrow: 'Журнал изменений', title: 'Обновления', description: 'Публичный журнал изменений продукта, данных и политик.', badge: 'Версия данных', releaseTitle: 'Версия платформы на шести языках', items: ['Опубликованы маршруты на английском, китайском, русском, немецком, французском и испанском.', 'Добавлены структурированные данные о вузах, программах, городах и стипендиях с источниками и сроками проверки.', 'Добавлены избранное, сравнение, защищённая обратная связь, многоязычное SEO и автоматические проверки качества данных.'] },
  legal: {
    privacy: { eyebrow: 'Обновлено: 16.07.2026', title: 'Политика конфиденциальности', intro: 'Сайт минимизирует сбор данных, не создаёт аккаунты и не хранит документы для поступления.', sections: [
      { title: 'Локальное хранение', paragraphs: ['Избранное и сравнение хранятся только в браузере и не загружаются на сайт. Очистка данных браузера удалит их.'] },
      { title: 'Форма обратной связи', paragraphs: ['Сообщение, необязательный email, страница и ссылка на источник приватно отправляются автору через Resend; база обращений не создаётся.'], items: ['Не отправляйте паспорт, оценки, медицинские, платёжные или иные документы.', 'IP преобразуется HMAC и используется только для лимита 5 сообщений в час; ключ истекает через час.'] },
      { title: 'Аналитика и третьи стороны', paragraphs: ['Используются Vercel Web Analytics и Speed Insights без рекламного отслеживания; Turnstile защищает от ботов, Resend доставляет почту.'] },
      { title: 'Контакт и удаление', paragraphs: ['Для запроса или удаления отправленного сообщения свяжитесь через форму и укажите данные для его идентификации.'] },
    ] },
    disclaimer: { eyebrow: 'Важная информация', title: 'Отказ от ответственности', intro: 'Это независимый некоммерческий справочник, не представляющий вуз, государство или стипендиальную организацию.', sections: [
      { title: 'Приоритет официальных данных', paragraphs: ['Сроки, цены, языковые требования, стипендии и визовые правила меняются. Перед подачей, оплатой или поездкой перепроверьте официальный источник.'] },
      { title: 'Нет гарантии поступления', paragraphs: ['Наличие в каталоге не является рекомендацией и не гарантирует право участия, поступление, визу или финансирование.'] },
      { title: 'Внешние ссылки', paragraphs: ['За внешние сайты отвечают их владельцы; этот проект не контролирует их содержание, доступность или приватность.'] },
    ] },
    dataPolicy: { eyebrow: 'Методика данных', title: 'Источники и обновления', intro: 'У каждого изменяемого факта должны быть источник, дата проверки, срок пересмотра и видимый статус.', sections: [
      { title: 'Приоритет источников', items: ['Приоритет — международные страницы вузов, официальные системы подачи и государственные сайты.', 'Соцсети, репосты и сторонние платформы — только подсказки, не доказательство сроков, цен или требований.'] },
      { title: 'Статусы', items: ['Проверено: сверено с актуальным официальным источником и может быть опубликовано.', 'Черновик: проверка не завершена; запись не попадает на публичные страницы и в поисковые системы.', 'Нужна проверка: срок пересмотра прошёл или есть противоречие; запись явно помечается.', 'Архив: запись сохраняется в истории данных, но не публикуется как актуальная.'] },
      { title: 'Неизвестные и старые данные', paragraphs: ['Необъявленные значения хранятся как null. Старые циклы архивируются, а не копируются в текущий год.'] },
      { title: 'График обновлений', items: ['Ссылки проверяются еженедельно; 403, 429 и тайм-ауты направляются на ручную проверку.', 'Ежемесячно создаётся отчёт качества; полная ручная проверка — в январе и августе–сентябре.', 'Автоматизация создаёт задачи, но не публикует факты о приёме.'] },
    ] },
  },
  footer: { project: 'Независимый некоммерческий гид. Приоритет всегда у официальных объявлений вузов.', creator: 'Автор Henry Yang', privacy: 'Конфиденциальность', disclaimer: 'Отказ от ответственности', dataPolicy: 'Политика данных', updates: 'Обновления' },
}

const de: BaseMessages = {
  brand: 'Studieren in China Atlas',
  shell: { brandTagline: 'Unabhängiger Studienatlas', navLabel: 'Hauptnavigation', mobileMenuLabel: 'Menü öffnen', skipLinkLabel: 'Zum Hauptinhalt springen', footerExplore: 'Entdecken', footerProject: 'Projekt', dataRelease: 'Datenstand', creatorPrefix: 'Erstellt von' },
  nav: { home: 'Start', universities: 'Universitäten', programs: 'Studiengänge', scholarships: 'Stipendien', cities: 'Städte', guides: 'Leitfäden', favorites: 'Merkliste', about: 'Über uns', contact: 'Kontakt' },
  common: { explore: 'Entdecken', viewDetails: 'Details ansehen', applyOfficial: 'Offiziell bewerben', officialSource: 'Offizielle Quelle', verified: 'Geprüft', stale: 'Prüfung fällig', draft: 'In Prüfung', archived: 'Archiviert', lastVerified: 'Geprüft am', unknown: 'Nicht bekannt gegeben', all: 'Alle', search: 'Suchen', clear: 'Filter löschen', save: 'Speichern', saved: 'Gespeichert', compare: 'Vergleichen', print: 'Drucken / als PDF speichern', back: 'Zurück', university: 'Universität', program: 'Studiengang', scholarship: 'Stipendium', city: 'Stadt', status: 'Status', openNow: 'Jetzt geöffnet', deadline: 'Bewerbungsfrist', tuition: 'Studiengebühren', duration: 'Dauer', months: 'Monate', language: 'Unterrichtssprache', requirements: 'Sprachanforderungen', translationPending: 'Übersetzung ausstehend', authoritativeNotice: 'Zulassungsinformationen können sich ändern. Prüfen Sie stets die verlinkte offizielle Seite.' },
  home: { eyebrow: 'Ein klarerer Weg zum Studium in China', title: 'Studiengänge vergleichen. Fristen verfolgen. Sicher entscheiden.', intro: 'Ein quellenbasierter Wegweiser zu chinesischen Universitäten, Stipendien, Bewerbungswegen und Studienstädten.', findUniversity: 'Universität finden', explorePrograms: 'Studiengänge entdecken', checkScholarships: 'Stipendien prüfen', learnCities: 'Städte kennenlernen', featured: 'Mit verlässlichen Grundlagen starten', featuredIntro: 'Entdecken Sie strukturierte Daten mit sichtbaren Quellen und Prüfdaten.', deadlineTitle: 'Wichtige Bewerbungszeiträume', disciplines: 'Nach Fachgebiet suchen', cityTitle: 'Zwölf Studienstädte, eine gemeinsame Reise', guideTitle: 'Ihre Bewerbung Schritt für Schritt', programVerificationNote: 'Studiengangsdaten werden einzeln geprüft. Entwürfe ohne offizielle Programmseite werden weder veröffentlicht noch indexiert.', sourceHeading: 'Jede Angabe sollte zu ihrer Quelle führen' },
  universities: { title: 'Universitäten', intro: 'Filtern Sie eine kuratierte landesweite Auswahl nach Stadt, Region und Fachgebiet.', searchPlaceholder: 'Universität, Stadt oder Fach suchen', noResults: 'Keine Universität entspricht diesen Filtern.', cityFilter: 'Stadt', regionFilter: 'Region', fieldFilter: 'Fachgebiet', results: 'Universitäten', programs: 'Studiengänge', funding: 'Passende Stipendien', facts: 'Universität im Überblick', sources: 'Quellen und Prüfung', review: 'Nächste Prüfung', official: 'Universitätswebsite', admission: 'Internationale Zulassung' },
  programs: { title: 'Studiengänge', intro: 'Vergleichen Sie Abschluss, Unterrichtssprache, Dauer und aktuellen Zulassungsstatus.', searchPlaceholder: 'Studiengang oder Universität suchen', noResults: 'Keine Studiengänge entsprechen diesen Filtern.', degree: 'Abschluss', discipline: 'Fachgebiet', languageFilter: 'Unterrichtssprache', statusFilter: 'Bewerbungsdaten', tuitionFilter: 'Gebührendaten', published: 'Veröffentlicht', unannounced: 'Nicht bekannt gegeben', known: 'Verfügbar', results: 'Studiengänge', verificationNote: 'Der öffentliche Katalog enthält nur geprüfte Einträge mit einer offiziellen Quelle auf Programmebene. Entwürfe sind von Produktionsseiten, Sitemap und strukturierten Daten ausgeschlossen.', overview: 'Programmdaten', cycle: 'Zulassungszeitraum', year: 'Studienjahr', intake: 'Studienbeginn', fee: 'Bewerbungsgebühr', opens: 'Öffnet am', sources: 'Offizielle Quellen und Prüfung', related: 'Weitere Studiengänge dieser Universität', university: 'Universität', faculty: 'Fakultät', qualification: 'Abschlussbezeichnung', studyMode: 'Studienform', languagePolicy: 'Sprachregelung', curriculum: 'Lehrplan-Schwerpunkte', eligibility: 'Zulassungsvoraussetzungen', materials: 'Bewerbungsunterlagen', campus: 'Campus', fullTime: 'Vollzeit', partTime: 'Teilzeit', hybrid: 'Hybrid', applicationStatus: 'Bewerbungsstatus', datePublished: 'Termine veröffentlicht', rolling: 'Laufende Zulassung', notAnnounced: 'Noch nicht bekannt gegeben', previousCycle: 'Referenz zum Vorjahr', applicationsClosed: 'Bewerbungsfrist abgelaufen', upcoming: 'Bald geöffnet', springIntake: 'Frühjahrsbeginn', autumnIntake: 'Herbstbeginn', otherIntake: 'Sonstiger Studienbeginn', tuitionProgram: 'pro Programm', tuitionSemester: 'pro Semester', tuitionAcademicYear: 'pro Studienjahr', tuitionMonth: 'pro Monat', tuitionOther: 'Offizielle Angaben beachten' },
  scholarships: { title: 'Stipendien', intro: 'Informieren Sie sich über Leistungen, Bewerbungswege und offizielle Links.', coverage: 'Leistungsumfang', stipend: 'Monatlicher Zuschuss', catalogueNotice: 'Der öffentliche Katalog zeigt nur anhand offizieller Quellen geprüfte Stipendien; ein Eintrag bedeutet nicht zwingend, dass Bewerbungen geöffnet sind.', tuition: 'Studiengebühren', accommodation: 'Unterkunft', insurance: 'Krankenversicherung', scope: 'Teilnehmende Universitäten', sources: 'Quellen und Prüfung', included: 'Enthalten', notIncluded: 'Nicht enthalten' },
  cities: { title: 'Studienstädte', intro: 'Sehen Sie die Verteilung der Universitäten und erhalten Sie einen kurzen Eindruck von Klima, Essen und Alltag.', climate: 'Klima im Überblick', food: 'Kulinarische Tipps', sights: 'Sehenswürdigkeiten', universities: 'Universitäten in dieser Stadt', mapNote: 'Dies ist ein Städteindex nach Längen- und Breitengrad, keine Karte; Grenzen werden nicht dargestellt. Eine geprüfte Standardkarte folgt, sobald regelkonforme Materialien und Genehmigungen vorliegen.', plotNote: 'Stadtmarkierungen sind ungefähre Orientierungspunkte.', officialMapService: 'Standardkartendienst des chinesischen Ministeriums für natürliche Ressourcen öffnen', contentTitle: 'Hinweis zu Stadtinformationen', contentNotice: 'Klima, Essen und Sehenswürdigkeiten dienen der kurzen Orientierung und sind keine Reise- oder Sicherheitsempfehlung.' },
  favorites: { title: 'Ihre Merkliste', intro: 'Auf diesem Gerät gespeichert. Vergleichen Sie bis zu vier Studiengänge.', empty: 'Sie haben noch keine Studiengänge gespeichert.', localOnly: 'Gespeicherte Einträge bleiben in diesem Browser und werden nicht hochgeladen.', loading: 'Merkliste dieses Geräts wird geladen…', choose: 'Zum Vergleich auswählen', limit: 'Wählen Sie bis zu vier Studiengänge.', comparison: 'Studiengangsvergleich', remove: 'Entfernen', university: 'Universität' },
  guide: { title: 'Bewerbungsleitfäden', intro: 'Praktische, quellenbewusste Checklisten von der Auswahl bis zur Ankunft.', eyebrow: 'Bewerbungsweg', usingTitle: 'Hinweise zu diesem Leitfaden', disclaimer: 'Dieser Leitfaden ersetzt keine offiziellen Anforderungen einer Universität, Stipendienstelle, eines Konsulats oder einer Einwanderungsbehörde.' },
  about: { title: 'Ein gemeinnütziger, evidenzbasierter Wegweiser', intro: 'Der Studieren in China Atlas bündelt verstreute offizielle Informationen zu einem transparenteren Ausgangspunkt.', mission: 'Warum es dieses Projekt gibt', missionText: 'Internationale Bewerber vergleichen häufig viele Seiten mit unterschiedlichen Formaten und Aktualisierungszyklen. Dieses Projekt erleichtert den Vergleich und hält die offizielle Quelle stets nur einen Klick entfernt.', creator: 'Über den Ersteller', creatorText: 'Von Henry Yang als nichtkommerzielles Informationsprojekt für internationale Studierende erstellt und gepflegt.', data: 'So werden Daten gepflegt', dataText: 'Fakten werden versioniert gespeichert, anhand offizieller Quellen geprüft und automatisch auf Überalterung und defekte Links kontrolliert.', creatorWebsite: 'Website des Erstellers', principlesTitle: 'Offen, nachvollziehbar und nichtkommerziell', versionedChanges: 'Versionierte Faktenänderungen', sourceLinkedFacts: 'Mit offiziellen Quellen verknüpft', publicLanguages: 'Öffentliche Oberflächensprachen', noAds: 'Werbung oder Affiliate-Links' },
  contact: { title: 'Kontakt und Korrekturen', intro: 'Melden Sie veraltete Angaben oder defekte Links oder schlagen Sie einen Studiengang vor. Bitte senden Sie keine Bewerbungsunterlagen.', category: 'Worum geht es?', incorrect: 'Falsche oder veraltete Daten', broken: 'Defekter Link', suggest: 'Studiengang vorschlagen', other: 'Sonstiges', message: 'Ihre Nachricht', source: 'Offizieller Quellenlink (optional)', email: 'E-Mail für Antwort (optional)', consent: 'Ich verstehe, dass dieses Formular nur für Feedback gedacht ist, und sende keine sensiblen Bewerbungsunterlagen.', submit: 'Feedback senden', sending: 'Wird gesendet…', success: 'Vielen Dank. Ihr Feedback wurde vertraulich gesendet.', error: 'Die Nachricht konnte nicht gesendet werden. Bitte versuchen Sie es später erneut.', configurationNote: 'Das vertrauliche Formular wird verfügbar, sobald Turnstile, Resend und die Umgebungsvariablen für die Ratenbegrenzung konfiguriert sind.', privacyTitle: 'Datenschutz zuerst', sensitiveNotice: 'Senden Sie keine Pässe, Zeugnisse, Gesundheitsdaten, Empfehlungsschreiben, Zulassungsunterlagen oder Zahlungsinformationen. Die private E-Mail-Adresse des Erstellers wird nicht veröffentlicht.', sourceSuggestion: 'Ein offizieller Quellenlink hilft uns, eine Korrektur schneller zu prüfen.', creatorWebsite: 'Website des Erstellers besuchen' },
  notFound: { title: 'Seite nicht gefunden', description: 'Der Link wurde möglicherweise geändert oder dieser Eintrag ist noch nicht veröffentlicht.', action: 'Zur Startseite' },
  updates: { eyebrow: 'Änderungsprotokoll', title: 'Aktualisierungen', description: 'Öffentliche Übersicht wichtiger Änderungen an Produkt, Daten und Richtlinien.', badge: 'Datenstand', releaseTitle: 'Plattformversion in sechs Sprachen', items: ['Routen auf Englisch, Chinesisch, Russisch, Deutsch, Französisch und Spanisch veröffentlicht.', 'Strukturierte Daten zu Universitäten, Studiengängen, Städten und Stipendien mit Quellen- und Prüfmetadaten ergänzt.', 'Merkliste, Vergleich, sicheres Feedback, mehrsprachiges SEO und automatisierte Datenqualitätsprüfungen ergänzt.'] },
  legal: {
    privacy: { eyebrow: 'Stand: 16. Juli 2026', title: 'Datenschutzerklärung', intro: 'Diese Website minimiert die Datenerhebung, erstellt keine Benutzerkonten und speichert keine Bewerbungsunterlagen.', sections: [
      { title: 'Lokale Speicherung', paragraphs: ['Favoriten und Vergleichsauswahlen bleiben in Ihrem Browser und werden nie hochgeladen. Beim Löschen der Browserdaten werden sie entfernt.'] },
      { title: 'Feedbackformular', paragraphs: ['Ihre Nachricht, optionale Antwort-E-Mail, Seite und Quellenlink werden über Resend vertraulich an den Ersteller gesendet. Es wird keine Feedbackdatenbank angelegt.'], items: ['Senden Sie keine Pässe, Zeugnisse, Gesundheitsdaten, Empfehlungen, Zahlungsdaten oder sonstige Bewerbungsunterlagen.', 'IP-Adressen werden per HMAC verarbeitet und nur für ein Limit von fünf Nachrichten pro Stunde genutzt; der Schlüssel verfällt nach einer Stunde.'] },
      { title: 'Analyse und Auftragsverarbeiter', paragraphs: ['Vercel Web Analytics und Speed Insights messen die Gesamtleistung ohne Werbetracking. Turnstile schützt vor Bots und Resend übermittelt Feedback.'] },
      { title: 'Kontakt und Löschung', paragraphs: ['Um gesendetes Feedback abzufragen oder löschen zu lassen, nutzen Sie das Kontaktformular und geben Sie genügend Informationen zur Identifizierung an.'] },
    ] },
    disclaimer: { eyebrow: 'Wichtiger Hinweis', title: 'Haftungsausschluss', intro: 'Dies ist ein unabhängiges, nichtkommerzielles Informationsprojekt. Es vertritt keine Universität, Regierung oder Stipendienorganisation.', sections: [
      { title: 'Offizielle Informationen haben Vorrang', paragraphs: ['Zulassungszeiträume, Gebühren, Sprachanforderungen, Stipendien und Visaregeln ändern sich. Prüfen Sie die verlinkte offizielle Quelle erneut, bevor Sie sich bewerben, zahlen oder reisen.'] },
      { title: 'Keine Zulassungs- oder Fördergarantie', paragraphs: ['Die Aufnahme einer Universität, eines Studiengangs oder Stipendiums ist keine Empfehlung und garantiert weder Berechtigung noch Zulassung, Visum oder Förderung.'] },
      { title: 'Externe Links', paragraphs: ['Externe Websites werden von ihren Betreibern kontrolliert. Dieses Projekt kann deren Inhalte, Verfügbarkeit oder Datenschutzpraktiken nicht steuern.'] },
    ] },
    dataPolicy: { eyebrow: 'Quellenbasierte Methodik', title: 'Datenquellen und Aktualisierungsrichtlinie', intro: 'Jede veränderliche Zulassungsangabe sollte eine Quelle, ein Prüfdatum, ein erneutes Prüfdatum und einen sichtbaren Status haben.', sections: [
      { title: 'Quellenhierarchie', items: ['Bevorzugt werden internationale Zulassungsseiten der Universitäten, offizielle Bewerbungssysteme und Regierungsseiten.', 'Soziale Medien, Weiterveröffentlichungen und Drittplattformen dienen nur als Hinweise; sie können Gebühren, Fristen oder Anforderungen nicht allein belegen.'] },
      { title: 'Bedeutung der Status', items: ['Geprüft: anhand einer aktuellen offiziellen Quelle kontrolliert und zur Veröffentlichung geeignet.', 'In Prüfung: noch nicht veröffentlichungsreif und von Produktionsseiten sowie Suchmaschinen ausgeschlossen.', 'Prüfung fällig: Prüfdatum überschritten oder widersprüchlich; der Eintrag bleibt deutlich gekennzeichnet.', 'Archiviert: im versionierten Datenverlauf erhalten, aber nicht als aktuelle Orientierung veröffentlicht.'] },
      { title: 'Unbekannte Angaben und frühere Zyklen', paragraphs: ['Nicht veröffentlichte Werte werden als null gespeichert und als nicht bekannt gegeben angezeigt. Frühere Zyklen werden archiviert und nie in ein aktuelles Jahr kopiert.'] },
      { title: 'Prüfrhythmus', items: ['Links werden wöchentlich geprüft; 403-, 429- und Timeout-Fehler werden zur manuellen Prüfung vorgemerkt.', 'Monatlich wird ein Datenqualitätsbericht erstellt; vollständige manuelle Prüfungen erfolgen im Januar und August–September.', 'Automatisierung erstellt Aufgaben, veröffentlicht aber niemals Zulassungsfakten automatisch.'] },
    ] },
  },
  footer: { project: 'Ein unabhängiger, nichtkommerzieller Wegweiser. Offizielle Mitteilungen der Universitäten haben stets Vorrang.', creator: 'Erstellt von Henry Yang', privacy: 'Datenschutz', disclaimer: 'Haftungsausschluss', dataPolicy: 'Datenrichtlinie', updates: 'Aktualisierungen' },
}

const fr: BaseMessages = {
  brand: 'Atlas des études en Chine',
  shell: { brandTagline: 'Atlas étudiant indépendant', navLabel: 'Navigation principale', mobileMenuLabel: 'Ouvrir le menu', skipLinkLabel: 'Aller au contenu principal', footerExplore: 'Explorer', footerProject: 'Projet', dataRelease: 'Version des données', creatorPrefix: 'Créé par' },
  nav: { home: 'Accueil', universities: 'Universités', programs: 'Programmes', scholarships: 'Bourses', cities: 'Villes', guides: 'Guides', favorites: 'Favoris', about: 'À propos', contact: 'Contact' },
  common: { explore: 'Explorer', viewDetails: 'Voir les détails', applyOfficial: 'Candidater sur le site officiel', officialSource: 'Source officielle', verified: 'Vérifié', stale: 'À vérifier', draft: 'En cours de vérification', archived: 'Archivé', lastVerified: 'Vérifié le', unknown: 'Non annoncé', all: 'Tous', search: 'Rechercher', clear: 'Effacer les filtres', save: 'Enregistrer', saved: 'Enregistré', compare: 'Comparer', print: 'Imprimer / enregistrer en PDF', back: 'Retour', university: 'Université', program: 'Programme', scholarship: 'Bourse', city: 'Ville', status: 'Statut', openNow: 'Ouvert maintenant', deadline: 'Date limite', tuition: 'Frais de scolarité', duration: 'Durée', months: 'mois', language: 'Langue d’enseignement', requirements: 'Exigences linguistiques', translationPending: 'Traduction en attente', authoritativeNotice: 'Les informations d’admission peuvent changer. Vérifiez toujours la page officielle liée.' },
  home: { eyebrow: 'Un parcours plus clair pour étudier en Chine', title: 'Comparez les programmes. Suivez les dates. Choisissez sereinement.', intro: 'Un guide sourcé des universités chinoises, bourses, voies de candidature et villes étudiantes.', findUniversity: 'Trouver une université', explorePrograms: 'Explorer les programmes', checkScholarships: 'Consulter les bourses', learnCities: 'Découvrir les villes', featured: 'Commencer par des informations fiables', featuredIntro: 'Consultez une première sélection structurée avec sources et dates de vérification visibles.', deadlineTitle: 'Périodes de candidature à suivre', disciplines: 'Explorer par domaine', cityTitle: 'Douze villes étudiantes, un même parcours', guideTitle: 'Votre candidature, étape par étape', programVerificationNote: 'Les programmes sont vérifiés un par un. Les brouillons sans page officielle ne sont ni publiés ni indexés.', sourceHeading: 'Chaque information doit mener à sa source' },
  universities: { title: 'Universités', intro: 'Filtrez une sélection nationale par ville, région et domaine d’études.', searchPlaceholder: 'Rechercher une université, une ville ou un domaine', noResults: 'Aucune université ne correspond à ces filtres.', cityFilter: 'Ville', regionFilter: 'Région', fieldFilter: 'Domaine', results: 'universités', programs: 'Programmes à explorer', funding: 'Bourses associées', facts: 'L’université en bref', sources: 'Sources et vérification', review: 'Révision prévue', official: 'Site de l’université', admission: 'Admissions internationales' },
  programs: { title: 'Programmes', intro: 'Comparez le niveau, la langue d’enseignement, la durée et le statut des admissions.', searchPlaceholder: 'Rechercher un programme ou une université', noResults: 'Aucun programme ne correspond à ces filtres.', degree: 'Niveau de diplôme', discipline: 'Domaine', languageFilter: 'Langue d’enseignement', statusFilter: 'Dates de candidature', tuitionFilter: 'Données sur les frais', published: 'Publiées', unannounced: 'Non annoncées', known: 'Disponibles', results: 'programmes', verificationNote: 'Le catalogue public n’accepte que les fiches vérifiées avec une source officielle au niveau du programme. Les brouillons sont exclus des pages publiques, du plan du site et des données structurées.', overview: 'Informations sur le programme', cycle: 'Cycle d’admission', year: 'Année universitaire', intake: 'Rentrée', fee: 'Frais de dossier', opens: 'Ouverture', sources: 'Sources officielles et vérification', related: 'Autres programmes de cette université', university: 'Université', faculty: 'Faculté', qualification: 'Diplôme obtenu', studyMode: 'Mode d’études', languagePolicy: 'Politique linguistique', curriculum: 'Points forts du cursus', eligibility: 'Conditions d’admission', materials: 'Pièces de candidature', campus: 'Campus', fullTime: 'Temps plein', partTime: 'Temps partiel', hybrid: 'Hybride', applicationStatus: 'Statut de candidature', datePublished: 'Dates publiées', rolling: 'Admissions continues', notAnnounced: 'Non annoncé', previousCycle: 'Référence au cycle précédent', applicationsClosed: 'Candidatures closes', upcoming: 'Ouverture prochaine', springIntake: 'Rentrée de printemps', autumnIntake: 'Rentrée d’automne', otherIntake: 'Autre rentrée', tuitionProgram: 'par programme', tuitionSemester: 'par semestre', tuitionAcademicYear: 'par année universitaire', tuitionMonth: 'par mois', tuitionOther: 'Voir les informations officielles' },
  scholarships: { title: 'Bourses', intro: 'Comprenez la couverture, les voies d’éligibilité et les liens de candidature officiels.', coverage: 'Couverture', stipend: 'Allocation mensuelle', catalogueNotice: 'Le catalogue public ne présente que les bourses vérifiées auprès de sources officielles ; une fiche ne signifie pas forcément que les candidatures sont ouvertes.', tuition: 'Frais de scolarité', accommodation: 'Hébergement', insurance: 'Assurance médicale', scope: 'Universités participantes', sources: 'Sources et vérification', included: 'Inclus', notIncluded: 'Non inclus' },
  cities: { title: 'Villes étudiantes', intro: 'Découvrez où se trouvent les universités et obtenez un aperçu du climat, de la cuisine et de la vie quotidienne.', climate: 'Climat en bref', food: 'À goûter', sights: 'À voir', universities: 'Universités dans cette ville', mapNote: 'Il s’agit d’un index de villes par latitude et longitude, non d’une carte ; aucune frontière n’est représentée. Une carte standard contrôlée sera ajoutée après obtention d’éléments conformes et des autorisations.', plotNote: 'Les marqueurs de ville sont approximatifs et indicatifs.', officialMapService: 'Consulter le service de cartes standard du ministère chinois des Ressources naturelles', contentTitle: 'À propos des informations urbaines', contentNotice: 'Le climat, la cuisine et les sites donnent un aperçu général et ne constituent pas un conseil de voyage ou de sécurité.' },
  favorites: { title: 'Votre sélection', intro: 'Enregistrée sur cet appareil. Comparez jusqu’à quatre programmes.', empty: 'Vous n’avez encore enregistré aucun programme.', localOnly: 'Les éléments restent dans ce navigateur et ne sont pas téléversés.', loading: 'Chargement de la sélection de cet appareil…', choose: 'Sélectionner pour comparer', limit: 'Choisissez jusqu’à quatre programmes.', comparison: 'Comparaison des programmes', remove: 'Retirer', university: 'Université' },
  guide: { title: 'Guides de candidature', intro: 'Des listes pratiques et attentives aux sources, de la présélection à l’arrivée.', eyebrow: 'Parcours de candidature', usingTitle: 'Utiliser ce guide', disclaimer: 'Ce guide ne remplace pas les exigences officielles d’une université, d’un organisme de bourse, d’un consulat ou d’une autorité d’immigration.' },
  about: { title: 'Un guide d’intérêt public fondé sur les sources', intro: 'L’Atlas des études en Chine organise des informations officielles dispersées en un point de départ plus transparent.', mission: 'Pourquoi ce projet existe', missionText: 'Les candidats internationaux comparent souvent des dizaines de pages aux formats et rythmes de mise à jour différents. Ce projet clarifie la comparaison tout en gardant la source officielle à un clic.', creator: 'À propos du créateur', creatorText: 'Créé et maintenu par Henry Yang comme projet d’information non commercial pour les étudiants internationaux.', data: 'Comment les données sont maintenues', dataText: 'Les faits sont conservés dans des fichiers versionnés, vérifiés auprès de sources officielles et contrôlés automatiquement pour repérer les données anciennes et les liens brisés.', creatorWebsite: 'Site du créateur', principlesTitle: 'Ouvert, traçable et non commercial', versionedChanges: 'Modifications des faits versionnées', sourceLinkedFacts: 'Faits liés aux sources officielles', publicLanguages: 'Langues publiques de l’interface', noAds: 'Publicités ou liens affiliés' },
  contact: { title: 'Contact et corrections', intro: 'Signalez une information ancienne, un lien brisé ou proposez un programme. N’envoyez pas de documents de candidature.', category: 'Quel est le sujet ?', incorrect: 'Donnée incorrecte ou ancienne', broken: 'Lien brisé', suggest: 'Proposer un programme', other: 'Autre', message: 'Votre message', source: 'Lien vers la source officielle (facultatif)', email: 'Adresse de réponse (facultatif)', consent: 'Je comprends que ce formulaire sert uniquement aux retours et je n’enverrai aucun document de candidature sensible.', submit: 'Envoyer', sending: 'Envoi…', success: 'Merci. Votre message a été envoyé de façon confidentielle.', error: 'Le message n’a pas pu être envoyé. Réessayez plus tard.', configurationNote: 'Le formulaire privé sera disponible après la configuration de Turnstile, Resend et des variables de limitation de débit.', privacyTitle: 'La confidentialité d’abord', sensitiveNotice: 'N’envoyez pas de passeport, relevé de notes, donnée médicale, lettre de recommandation, document d’admission ou information de paiement. L’adresse privée du créateur n’est pas publiée.', sourceSuggestion: 'Ajouter un lien officiel nous aide à vérifier une correction plus rapidement.', creatorWebsite: 'Visiter le site du créateur' },
  notFound: { title: 'Page introuvable', description: 'Le lien a peut-être changé ou cette fiche n’a pas encore été publiée.', action: 'Retour à l’accueil' },
  updates: { eyebrow: 'Journal des modifications', title: 'Mises à jour', description: 'Un registre public des changements importants apportés au produit, aux données et aux politiques.', badge: 'Version des données', releaseTitle: 'Version de la plateforme en six langues', items: ['Publication des routes en anglais, chinois, russe, allemand, français et espagnol.', 'Ajout de données structurées sur les universités, programmes, villes et bourses, avec sources et métadonnées de révision.', 'Ajout des favoris, de la comparaison, du formulaire sécurisé, du SEO multilingue et des contrôles automatiques de qualité des données.'] },
  legal: {
    privacy: { eyebrow: 'Dernière mise à jour : 16 juillet 2026', title: 'Politique de confidentialité', intro: 'Ce site réduit la collecte de données au minimum, ne crée aucun compte et ne stocke aucun document de candidature.', sections: [
      { title: 'Stockage local', paragraphs: ['Les favoris et sélections de comparaison restent dans votre navigateur et ne sont jamais téléversés. Effacer les données du navigateur les supprime.'] },
      { title: 'Formulaire de contact', paragraphs: ['Votre message, l’adresse de réponse facultative, la page et le lien source sont envoyés confidentiellement au créateur via Resend. Aucune base de retours n’est créée.'], items: ['N’envoyez pas de passeport, relevé, dossier médical, recommandation, donnée de paiement ou autre pièce de candidature.', 'Les adresses IP sont traitées par HMAC uniquement pour limiter à cinq envois par heure ; la clé expire après une heure.'] },
      { title: 'Analyse et sous-traitants', paragraphs: ['Vercel Web Analytics et Speed Insights mesurent les performances globales sans suivi publicitaire. Turnstile bloque les robots et Resend transmet les messages.'] },
      { title: 'Contact et suppression', paragraphs: ['Pour consulter ou supprimer un retour envoyé, utilisez le formulaire et fournissez assez d’informations pour l’identifier.'] },
    ] },
    disclaimer: { eyebrow: 'Avis important', title: 'Avertissement', intro: 'Il s’agit d’un projet d’information indépendant et non commercial. Il ne représente aucune université, administration ou organisation de bourse.', sections: [
      { title: 'Les informations officielles priment', paragraphs: ['Les cycles, frais, exigences linguistiques, bourses et règles de visa changent. Vérifiez-les à nouveau sur la source officielle liée avant de candidater, payer ou voyager.'] },
      { title: 'Aucune garantie d’admission ou de financement', paragraphs: ['La présence d’une université, d’un programme ou d’une bourse ne constitue pas une recommandation et ne garantit ni l’éligibilité, ni l’admission, ni le visa, ni le financement.'] },
      { title: 'Liens externes', paragraphs: ['Les sites externes sont gérés par leurs opérateurs. Ce projet ne contrôle ni leur contenu, ni leur disponibilité, ni leurs pratiques de confidentialité.'] },
    ] },
    dataPolicy: { eyebrow: 'Méthode fondée sur les sources', title: 'Sources et politique de mise à jour', intro: 'Chaque donnée d’admission susceptible de changer doit avoir une source, une date de vérification, une date de révision et un statut visible.', sections: [
      { title: 'Hiérarchie des sources', items: ['Privilégier les pages d’admission internationale des universités, les systèmes officiels de candidature et les pages gouvernementales.', 'Les réseaux sociaux, republications et plateformes tierces servent uniquement de pistes ; ils ne peuvent pas justifier seuls des frais, dates ou exigences.'] },
      { title: 'Signification des statuts', items: ['Vérifié : contrôlé auprès d’une source officielle actuelle et publiable.', 'En cours de vérification : non validé pour publication et exclu des pages publiques et moteurs de recherche.', 'À vérifier : date de révision dépassée ou information contradictoire ; la fiche reste clairement signalée.', 'Archivé : conservé dans l’historique versionné, mais non publié comme conseil actuel.'] },
      { title: 'Valeurs inconnues et cycles précédents', paragraphs: ['Les valeurs non annoncées sont enregistrées comme null et affichées comme telles. Les cycles précédents sont archivés, jamais copiés vers une année actuelle.'] },
      { title: 'Rythme de révision', items: ['Les liens sont vérifiés chaque semaine ; les erreurs 403, 429 et délais dépassés deviennent des tâches manuelles.', 'Un rapport de santé des données est créé chaque mois ; une révision manuelle complète a lieu en janvier et en août–septembre.', 'L’automatisation crée des tâches mais ne publie jamais automatiquement des faits d’admission.'] },
    ] },
  },
  footer: { project: 'Un guide indépendant et non commercial. Les avis officiels des universités priment toujours.', creator: 'Créé par Henry Yang', privacy: 'Confidentialité', disclaimer: 'Avertissement', dataPolicy: 'Politique des données', updates: 'Mises à jour' },
}

const es: BaseMessages = {
  brand: 'Atlas para estudiar en China',
  shell: { brandTagline: 'Atlas estudiantil independiente', navLabel: 'Navegación principal', mobileMenuLabel: 'Abrir menú', skipLinkLabel: 'Saltar al contenido principal', footerExplore: 'Explorar', footerProject: 'Proyecto', dataRelease: 'Versión de datos', creatorPrefix: 'Creado por' },
  nav: { home: 'Inicio', universities: 'Universidades', programs: 'Programas', scholarships: 'Becas', cities: 'Ciudades', guides: 'Guías', favorites: 'Guardados', about: 'Acerca de', contact: 'Contacto' },
  common: { explore: 'Explorar', viewDetails: 'Ver detalles', applyOfficial: 'Solicitar en el sitio oficial', officialSource: 'Fuente oficial', verified: 'Verificado', stale: 'Revisión pendiente', draft: 'En verificación', archived: 'Archivado', lastVerified: 'Verificado el', unknown: 'No anunciado', all: 'Todos', search: 'Buscar', clear: 'Borrar filtros', save: 'Guardar', saved: 'Guardado', compare: 'Comparar', print: 'Imprimir / guardar PDF', back: 'Volver', university: 'Universidad', program: 'Programa', scholarship: 'Beca', city: 'Ciudad', status: 'Estado', openNow: 'Abierto ahora', deadline: 'Fecha límite', tuition: 'Matrícula', duration: 'Duración', months: 'meses', language: 'Idioma de enseñanza', requirements: 'Requisitos de idioma', translationPending: 'Traducción pendiente', authoritativeNotice: 'La información de admisión puede cambiar. Confírmala siempre en la página oficial enlazada.' },
  home: { eyebrow: 'Un camino más claro para estudiar en China', title: 'Compara programas. Sigue los plazos. Elige con confianza.', intro: 'Una guía con fuentes sobre universidades chinas, becas, vías de solicitud y ciudades estudiantiles.', findUniversity: 'Buscar una universidad', explorePrograms: 'Explorar programas', checkScholarships: 'Consultar becas', learnCities: 'Conocer ciudades', featured: 'Empieza con información fiable', featuredIntro: 'Consulta una primera selección estructurada con fuentes y fechas de revisión visibles.', deadlineTitle: 'Periodos de solicitud importantes', disciplines: 'Explorar por área', cityTitle: 'Doce ciudades estudiantiles, un viaje conectado', guideTitle: 'Tu solicitud, paso a paso', programVerificationNote: 'Los programas se verifican uno por uno. Los borradores sin una página oficial no se publican ni se indexan.', sourceHeading: 'Cada dato debe conducir a su fuente' },
  universities: { title: 'Universidades', intro: 'Filtra una selección nacional por ciudad, región y área académica.', searchPlaceholder: 'Buscar universidad, ciudad o área', noResults: 'Ninguna universidad coincide con estos filtros.', cityFilter: 'Ciudad', regionFilter: 'Región', fieldFilter: 'Área', results: 'universidades', programs: 'Programas disponibles', funding: 'Becas relacionadas', facts: 'La universidad de un vistazo', sources: 'Fuentes y revisión', review: 'Próxima revisión', official: 'Sitio de la universidad', admission: 'Admisiones internacionales' },
  programs: { title: 'Programas', intro: 'Compara nivel, idioma de enseñanza, duración y estado actual de admisión.', searchPlaceholder: 'Buscar programa o universidad', noResults: 'Ningún programa coincide con estos filtros.', degree: 'Nivel académico', discipline: 'Área', languageFilter: 'Idioma de enseñanza', statusFilter: 'Fechas de solicitud', tuitionFilter: 'Datos de matrícula', published: 'Publicadas', unannounced: 'No anunciadas', known: 'Disponibles', results: 'programas', verificationNote: 'El catálogo público solo acepta registros verificados con una fuente oficial a nivel de programa. Los borradores se excluyen de las páginas públicas, el mapa del sitio y los datos estructurados.', overview: 'Datos del programa', cycle: 'Ciclo de admisión', year: 'Año académico', intake: 'Convocatoria', fee: 'Tasa de solicitud', opens: 'Apertura', sources: 'Fuentes oficiales y revisión', related: 'Otros programas de esta universidad', university: 'Universidad', faculty: 'Facultad', qualification: 'Titulación', studyMode: 'Modalidad de estudio', languagePolicy: 'Política lingüística', curriculum: 'Aspectos destacados del plan', eligibility: 'Requisitos de acceso', materials: 'Documentos de solicitud', campus: 'Campus', fullTime: 'Tiempo completo', partTime: 'Tiempo parcial', hybrid: 'Híbrido', applicationStatus: 'Estado de solicitud', datePublished: 'Fechas publicadas', rolling: 'Admisión continua', notAnnounced: 'No anunciado', previousCycle: 'Referencia del ciclo anterior', applicationsClosed: 'Solicitudes cerradas', upcoming: 'Próxima apertura', springIntake: 'Ingreso de primavera', autumnIntake: 'Ingreso de otoño', otherIntake: 'Otro ingreso', tuitionProgram: 'por programa', tuitionSemester: 'por semestre', tuitionAcademicYear: 'por año académico', tuitionMonth: 'por mes', tuitionOther: 'Consulta la información oficial' },
  scholarships: { title: 'Becas', intro: 'Consulta la cobertura, las vías de elegibilidad y los enlaces oficiales de solicitud.', coverage: 'Cobertura', stipend: 'Estipendio mensual', catalogueNotice: 'El catálogo público solo muestra becas verificadas con fuentes oficiales; que aparezca una beca no significa necesariamente que la convocatoria esté abierta.', tuition: 'Matrícula', accommodation: 'Alojamiento', insurance: 'Seguro médico', scope: 'Universidades participantes', sources: 'Fuentes y revisión', included: 'Incluido', notIncluded: 'No incluido' },
  cities: { title: 'Ciudades estudiantiles', intro: 'Descubre dónde están las universidades y obtén una breve idea del clima, la comida y la vida diaria.', climate: 'Clima de un vistazo', food: 'Qué probar', sights: 'Qué visitar', universities: 'Universidades en esta ciudad', mapNote: 'Este es un índice de ciudades por latitud y longitud, no un mapa, y no representa fronteras. Se añadirá un mapa estándar revisado cuando se obtengan recursos conformes y autorización.', plotNote: 'Los marcadores de ciudad son aproximados e informativos.', officialMapService: 'Consultar el servicio de mapas estándar del Ministerio de Recursos Naturales de China', contentTitle: 'Sobre el contenido de las ciudades', contentNotice: 'El clima, la comida y los lugares ofrecen una orientación breve, no consejos de viaje o seguridad.' },
  favorites: { title: 'Tu lista', intro: 'Guardada en este dispositivo. Compara hasta cuatro programas.', empty: 'Todavía no has guardado ningún programa.', localOnly: 'Los elementos permanecen en este navegador y no se suben.', loading: 'Cargando la lista de este dispositivo…', choose: 'Seleccionar para comparar', limit: 'Elige hasta cuatro programas.', comparison: 'Comparación de programas', remove: 'Eliminar', university: 'Universidad' },
  guide: { title: 'Guías de solicitud', intro: 'Listas prácticas y conscientes de las fuentes, desde la selección hasta la llegada.', eyebrow: 'Ruta de solicitud', usingTitle: 'Al usar esta guía', disclaimer: 'Esta guía no sustituye los requisitos oficiales de una universidad, organismo de becas, consulado o autoridad migratoria.' },
  about: { title: 'Una guía de interés público basada en fuentes', intro: 'El Atlas para estudiar en China organiza información oficial dispersa en un punto de partida más transparente.', mission: 'Por qué existe este proyecto', missionText: 'Los solicitantes internacionales suelen comparar decenas de páginas con formatos y ciclos de actualización distintos. Este proyecto facilita la comparación y mantiene la fuente oficial a un clic.', creator: 'Sobre el creador', creatorText: 'Creado y mantenido por Henry Yang como proyecto informativo no comercial para estudiantes internacionales.', data: 'Cómo se mantienen los datos', dataText: 'Los datos se guardan en archivos con control de versiones, se revisan con fuentes oficiales y se comprueban automáticamente para detectar antigüedad y enlaces rotos.', creatorWebsite: 'Sitio del creador', principlesTitle: 'Abierto, trazable y no comercial', versionedChanges: 'Cambios de datos versionados', sourceLinkedFacts: 'Datos enlazados a fuentes oficiales', publicLanguages: 'Idiomas públicos de la interfaz', noAds: 'Anuncios o enlaces de afiliados' },
  contact: { title: 'Contacto y correcciones', intro: 'Informa de datos desactualizados, enlaces rotos o sugiere un programa. No envíes documentos de solicitud.', category: '¿De qué se trata?', incorrect: 'Dato incorrecto o desactualizado', broken: 'Enlace roto', suggest: 'Sugerir un programa', other: 'Otro', message: 'Tu mensaje', source: 'Enlace a la fuente oficial (opcional)', email: 'Correo para responder (opcional)', consent: 'Entiendo que este formulario es solo para comentarios y no enviaré documentos sensibles de solicitud.', submit: 'Enviar', sending: 'Enviando…', success: 'Gracias. Tu mensaje se envió de forma privada.', error: 'No se pudo enviar el mensaje. Inténtalo de nuevo más tarde.', configurationNote: 'El formulario privado estará disponible después de configurar Turnstile, Resend y las variables de límite de frecuencia.', privacyTitle: 'La privacidad primero', sensitiveNotice: 'No envíes pasaportes, expedientes, datos de salud, cartas de recomendación, documentos de admisión ni información de pago. El correo privado del creador no se publica.', sourceSuggestion: 'Añadir una fuente oficial nos ayuda a verificar una corrección más rápido.', creatorWebsite: 'Visitar el sitio del creador' },
  notFound: { title: 'Página no encontrada', description: 'Es posible que el enlace haya cambiado o que este registro aún no se haya publicado.', action: 'Volver al inicio' },
  updates: { eyebrow: 'Registro de cambios', title: 'Actualizaciones', description: 'Un registro público de cambios importantes en el producto, los datos y las políticas.', badge: 'Versión de datos', releaseTitle: 'Versión de la plataforma en seis idiomas', items: ['Publicadas las rutas en inglés, chino, ruso, alemán, francés y español.', 'Añadidos datos estructurados de universidades, programas, ciudades y becas con fuentes y metadatos de revisión.', 'Añadidos favoritos, comparación, comentarios seguros, SEO multilingüe y controles automáticos de calidad de datos.'] },
  legal: {
    privacy: { eyebrow: 'Última actualización: 16 de julio de 2026', title: 'Política de privacidad', intro: 'Este sitio minimiza la recopilación de datos, no crea cuentas de usuario ni almacena documentos de solicitud.', sections: [
      { title: 'Almacenamiento local', paragraphs: ['Los favoritos y las selecciones de comparación permanecen en tu navegador y nunca se suben. Al borrar los datos del navegador se eliminan.'] },
      { title: 'Formulario de comentarios', paragraphs: ['Tu mensaje, correo opcional, página y enlace fuente se envían de forma privada al creador mediante Resend. No se crea una base de datos de comentarios.'], items: ['No envíes pasaportes, expedientes, historiales médicos, recomendaciones, datos de pago u otros documentos de solicitud.', 'Las direcciones IP se procesan con HMAC solo para limitar a cinco envíos por hora; la clave caduca tras una hora.'] },
      { title: 'Analítica y proveedores', paragraphs: ['Vercel Web Analytics y Speed Insights miden el rendimiento agregado sin seguimiento publicitario. Turnstile previene robots y Resend entrega los mensajes.'] },
      { title: 'Contacto y eliminación', paragraphs: ['Para consultar o eliminar comentarios enviados, usa el formulario y aporta información suficiente para identificarlos.'] },
    ] },
    disclaimer: { eyebrow: 'Aviso importante', title: 'Aviso legal', intro: 'Este es un proyecto informativo independiente y no comercial. No representa a ninguna universidad, gobierno u organismo de becas.', sections: [
      { title: 'La información oficial tiene prioridad', paragraphs: ['Los ciclos, tasas, requisitos lingüísticos, becas y normas de visado cambian. Confírmalos de nuevo en la fuente oficial enlazada antes de solicitar, pagar o viajar.'] },
      { title: 'Sin garantía de admisión o financiación', paragraphs: ['Incluir una universidad, programa o beca no supone una recomendación ni garantiza elegibilidad, admisión, visado o financiación.'] },
      { title: 'Enlaces externos', paragraphs: ['Los sitios externos están controlados por sus operadores. Este proyecto no puede controlar su contenido, disponibilidad o prácticas de privacidad.'] },
    ] },
    dataPolicy: { eyebrow: 'Metodología basada en fuentes', title: 'Fuentes y política de actualización', intro: 'Cada dato cambiante de admisión debe tener fuente, fecha de verificación, fecha de revisión y estado visible.', sections: [
      { title: 'Jerarquía de fuentes', items: ['Se priorizan las páginas de admisiones internacionales de universidades, los sistemas oficiales de solicitud y las páginas gubernamentales.', 'Las redes sociales, republicaciones y plataformas de terceros solo sirven como pistas; no pueden respaldar por sí solas tasas, fechas o requisitos.'] },
      { title: 'Significado de los estados', items: ['Verificado: comprobado con una fuente oficial vigente y apto para publicación.', 'En verificación: sin revisión de publicación y excluido de las páginas públicas y buscadores.', 'Revisión pendiente: superó su fecha de revisión o presenta conflictos; permanece claramente marcado.', 'Archivado: conservado en el historial versionado, no publicado como orientación actual.'] },
      { title: 'Datos desconocidos y ciclos anteriores', paragraphs: ['Los valores no anunciados se guardan como null y se muestran como no anunciados. Los ciclos anteriores se archivan y nunca se copian a un año actual.'] },
      { title: 'Frecuencia de revisión', items: ['Los enlaces se revisan semanalmente; los errores 403, 429 y tiempos de espera generan tareas de revisión manual.', 'Cada mes se crea un informe de salud de datos; las revisiones manuales completas se realizan en enero y agosto–septiembre.', 'La automatización crea tareas, pero nunca publica datos de admisión automáticamente.'] },
    ] },
  },
  footer: { project: 'Una guía independiente y no comercial. Los avisos oficiales de las universidades siempre tienen prioridad.', creator: 'Creado por Henry Yang', privacy: 'Privacidad', disclaimer: 'Aviso legal', dataPolicy: 'Política de datos', updates: 'Actualizaciones' },
}

const baseDictionaries = { en, zh, ru, de, fr, es } satisfies Record<LaunchLocale, BaseMessages>

const programExtraMessages: Record<LaunchLocale, ProgramExtraMessages> = {
  en: { viewApplicationPortal: 'View official application portal', tuitionReference: 'Reference amount—confirm with university', evidenceBasis: 'Evidence basis', cycleSpecific: 'Cycle-specific official notice', recurringRule: 'Official recurring annual rule' },
  zh: { viewApplicationPortal: '查看官方申请系统', tuitionReference: '参考金额——请向大学确认', evidenceBasis: '信息依据', cycleSpecific: '当期官方通知', recurringRule: '官方年度常规规则' },
  ru: { viewApplicationPortal: 'Открыть официальную систему подачи заявлений', tuitionReference: 'Ориентировочная сумма — уточните в университете', evidenceBasis: 'Основание данных', cycleSpecific: 'Официальное уведомление для конкретного цикла', recurringRule: 'Официальное ежегодно действующее правило' },
  de: { viewApplicationPortal: 'Offizielles Bewerbungsportal öffnen', tuitionReference: 'Referenzbetrag – bitte bei der Universität bestätigen', evidenceBasis: 'Datengrundlage', cycleSpecific: 'Offizielle Mitteilung für den jeweiligen Zulassungszeitraum', recurringRule: 'Offizielle jährlich wiederkehrende Regelung' },
  fr: { viewApplicationPortal: 'Accéder au portail officiel de candidature', tuitionReference: 'Montant indicatif — à confirmer auprès de l’université', evidenceBasis: 'Base documentaire', cycleSpecific: 'Avis officiel propre au cycle', recurringRule: 'Règle officielle renouvelée chaque année' },
  es: { viewApplicationPortal: 'Abrir el portal oficial de solicitudes', tuitionReference: 'Importe de referencia: confírmalo con la universidad', evidenceBasis: 'Base documental', cycleSpecific: 'Aviso oficial específico del ciclo', recurringRule: 'Norma oficial recurrente anual' },
}

export const dictionaries = Object.fromEntries(
  (Object.entries(baseDictionaries) as Array<[LaunchLocale, BaseMessages]>).map(([locale, messages]) => [
    locale,
    { ...messages, programs: { ...messages.programs, ...programExtraMessages[locale] } },
  ]),
) as Record<LaunchLocale, Messages>

export function getMessages(locale: LaunchLocale): Messages {
  return dictionaries[locale]
}
