import type { LaunchLocale } from './config'

const en = {
  brand: 'Study in China Atlas',
  nav: { home: 'Home', universities: 'Universities', programs: 'Programs', scholarships: 'Scholarships', cities: 'Cities', guides: 'Guides', favorites: 'Saved', about: 'About', contact: 'Contact' },
  common: { explore: 'Explore', viewDetails: 'View details', applyOfficial: 'Apply on official site', officialSource: 'Official source', verified: 'Verified', stale: 'Needs review', draft: 'Being verified', archived: 'Archived', lastVerified: 'Verified on', unknown: 'Not announced', all: 'All', search: 'Search', clear: 'Clear filters', save: 'Save', saved: 'Saved', compare: 'Compare', print: 'Print / Save PDF', back: 'Back', university: 'University', program: 'Program', scholarship: 'Scholarship', city: 'City', openNow: 'Open now', deadline: 'Deadline', tuition: 'Tuition', duration: 'Duration', months: 'months', language: 'Teaching language', requirements: 'Language requirements', translationPending: 'Translation pending', authoritativeNotice: 'Admissions information changes. Always confirm on the linked official page.' },
  home: { eyebrow: 'A clearer path to studying in China', title: 'Compare programs. Track deadlines. Choose with confidence.', intro: 'A source-backed guide for international students exploring Chinese universities, scholarships, application routes and student cities.', findUniversity: 'Find a university', explorePrograms: 'Explore programs', checkScholarships: 'Check scholarships', learnCities: 'Learn about cities', featured: 'Start with trusted essentials', featuredIntro: 'Browse a carefully structured first release, with visible sources and review dates.', deadlineTitle: 'Application windows to watch', disciplines: 'Explore by field', cityTitle: 'Twelve student cities, one connected journey', guideTitle: 'Your application, step by step' },
  universities: { title: 'Universities', intro: 'Filter a curated national selection by city, region and academic field.', searchPlaceholder: 'Search university, city or field', noResults: 'No universities match these filters.' },
  programs: { title: 'Programs', intro: 'Compare degree level, teaching language, duration and current admissions status.', searchPlaceholder: 'Search program or university', noResults: 'No programs match these filters.', degree: 'Degree level', discipline: 'Field' },
  scholarships: { title: 'Scholarships', intro: 'Understand coverage, eligibility routes and official application links.', coverage: 'Coverage', stipend: 'Monthly stipend' },
  cities: { title: 'Student cities', intro: 'See where universities are located and get a concise feel for climate, food and everyday life.', climate: 'Climate at a glance', food: 'What to taste', sights: 'What to see', universities: 'Universities in this city', mapNote: 'City distribution is shown on an approved standard-map base. Markers are informational.' },
  favorites: { title: 'Your shortlist', intro: 'Saved on this device. Select up to four programs for a compact comparison.', empty: 'You have not saved any programs yet.', localOnly: 'Saved items stay in this browser and are not uploaded.' },
  guide: { title: 'Application guides', intro: 'Practical, source-conscious checklists from shortlisting to arrival.' },
  about: { title: 'A public-interest guide built around evidence', intro: 'Study in China Atlas organizes scattered official information into a more transparent starting point.', mission: 'Why this exists', missionText: 'International applicants often compare dozens of pages with different formats and update cycles. This project makes the comparison clearer while keeping the official source one click away.', creator: 'About the creator', creatorText: 'Created and maintained by Henry Yang as a non-commercial information project for international students.', data: 'How data is maintained', dataText: 'Facts are stored in version-controlled files, reviewed against official sources, and automatically checked for staleness and broken links.' },
  contact: { title: 'Contact and corrections', intro: 'Report outdated information, a broken link, or suggest a program. Please do not send application documents.', category: 'What is this about?', incorrect: 'Incorrect or outdated data', broken: 'Broken link', suggest: 'Suggest a program', other: 'Other', message: 'Your message', source: 'Official source link (optional)', email: 'Reply email (optional)', consent: 'I understand this form is only for feedback and I will not submit sensitive application documents.', submit: 'Send feedback', sending: 'Sending…', success: 'Thank you. Your feedback was sent privately.', error: 'The message could not be sent. Please try again later.' },
  footer: { project: 'An independent, non-commercial guide. Official university notices always take priority.', creator: 'Created by Henry Yang', privacy: 'Privacy', disclaimer: 'Disclaimer', dataPolicy: 'Data policy', updates: 'Updates' },
}

const zh: typeof en = {
  brand: '中国留学指南',
  nav: { home: '首页', universities: '大学', programs: '项目', scholarships: '奖学金', cities: '城市', guides: '申请指南', favorites: '收藏', about: '关于', contact: '联系' },
  common: { explore: '开始探索', viewDetails: '查看详情', applyOfficial: '前往官网申请', officialSource: '官方来源', verified: '已核验', stale: '需要复核', draft: '核验中', archived: '已归档', lastVerified: '核验日期', unknown: '尚未公布', all: '全部', search: '搜索', clear: '清除筛选', save: '收藏', saved: '已收藏', compare: '对比', print: '打印 / 另存为 PDF', back: '返回', university: '大学', program: '项目', scholarship: '奖学金', city: '城市', openNow: '开放申请', deadline: '截止日期', tuition: '学费', duration: '学制', months: '个月', language: '授课语言', requirements: '语言要求', translationPending: '翻译待补充', authoritativeNotice: '招生信息可能变化，请始终以所链接的学校官方公告为准。' },
  home: { eyebrow: '更清晰的中国留学路径', title: '比较项目，掌握时间，安心选择。', intro: '为国际学生整理中国高校、奖学金、申请路径与留学城市信息，并为关键事实标注来源。', findUniversity: '寻找大学', explorePrograms: '浏览项目', checkScholarships: '查看奖学金', learnCities: '了解城市', featured: '从可信的核心信息开始', featuredIntro: '浏览结构化的首批资料，每条信息均显示来源与核验时间。', deadlineTitle: '值得关注的申请窗口', disciplines: '按学科探索', cityTitle: '十二座留学城市，一段中国旅程', guideTitle: '申请流程，一步一步完成' },
  universities: { title: '中国大学', intro: '按城市、地区和学科筛选精选高校。', searchPlaceholder: '搜索学校、城市或学科', noResults: '没有符合当前条件的大学。' },
  programs: { title: '学习项目', intro: '比较学位、授课语言、学制和当前申请状态。', searchPlaceholder: '搜索项目或大学', noResults: '没有符合当前条件的项目。', degree: '学位类型', discipline: '学科领域' },
  scholarships: { title: '奖学金', intro: '了解资助范围、申请渠道和官方申请链接。', coverage: '资助范围', stipend: '每月生活费' },
  cities: { title: '留学城市', intro: '查看大学分布，并快速了解气候、美食与城市生活。', climate: '气候概览', food: '当地美食', sights: '城市风景', universities: '本市大学', mapNote: '城市分布基于经审核的标准地图底图，标记仅供信息参考。' },
  favorites: { title: '我的收藏', intro: '收藏保存在当前设备，可选择最多四个项目进行对比。', empty: '你还没有收藏任何项目。', localOnly: '收藏只保存在本浏览器，不会上传。' },
  guide: { title: '申请指南', intro: '从选校到入境的实用、可核验清单。' },
  about: { title: '以证据为基础的公益留学指南', intro: '中国留学指南把分散的官方信息整理成透明、清晰的起点。', mission: '为什么创建这个网站', missionText: '国际申请者往往需要比较格式和更新时间各不相同的众多页面。本项目让比较更清楚，同时始终保留直达官方来源的链接。', creator: '关于创作者', creatorText: '由 Henry Yang 创建并维护，是一个面向国际学生的非商业信息项目。', data: '数据如何维护', dataText: '事实信息保存在可追踪版本的文件中，通过官方来源人工核验，并自动检查过期时间与失效链接。' },
  contact: { title: '联系与纠错', intro: '报告过期信息、失效链接或推荐项目。请不要发送申请文件。', category: '反馈类型', incorrect: '错误或过期信息', broken: '失效链接', suggest: '推荐项目', other: '其他', message: '反馈内容', source: '官方来源链接（可选）', email: '回复邮箱（可选）', consent: '我了解此表单仅用于反馈，并且不会提交任何敏感申请文件。', submit: '发送反馈', sending: '发送中…', success: '谢谢，反馈已私密发送。', error: '暂时无法发送，请稍后重试。' },
  footer: { project: '独立、非商业信息指南；请始终以大学官方公告为准。', creator: '创作者 Henry Yang', privacy: '隐私', disclaimer: '免责声明', dataPolicy: '数据政策', updates: '更新记录' },
}

const ru: typeof en = {
  brand: 'Атлас учёбы в Китае',
  nav: { home: 'Главная', universities: 'Вузы', programs: 'Программы', scholarships: 'Стипендии', cities: 'Города', guides: 'Поступление', favorites: 'Сохранённое', about: 'О проекте', contact: 'Связаться' },
  common: { explore: 'Открыть', viewDetails: 'Подробнее', applyOfficial: 'Подать на официальном сайте', officialSource: 'Официальный источник', verified: 'Проверено', stale: 'Нужна проверка', draft: 'Проверяется', archived: 'Архив', lastVerified: 'Проверено', unknown: 'Не объявлено', all: 'Все', search: 'Поиск', clear: 'Сбросить', save: 'Сохранить', saved: 'Сохранено', compare: 'Сравнить', print: 'Печать / PDF', back: 'Назад', university: 'Университет', program: 'Программа', scholarship: 'Стипендия', city: 'Город', openNow: 'Приём открыт', deadline: 'Срок подачи', tuition: 'Стоимость', duration: 'Длительность', months: 'месяцев', language: 'Язык обучения', requirements: 'Языковые требования', translationPending: 'Перевод готовится', authoritativeNotice: 'Условия поступления меняются. Всегда сверяйтесь с официальной страницей по ссылке.' },
  home: { eyebrow: 'Понятный путь к учёбе в Китае', title: 'Сравнивайте программы. Следите за сроками. Выбирайте уверенно.', intro: 'Путеводитель по китайским вузам, стипендиям, поступлению и студенческим городам с указанием источников.', findUniversity: 'Найти вуз', explorePrograms: 'Смотреть программы', checkScholarships: 'Найти стипендию', learnCities: 'Узнать о городах', featured: 'Начните с проверенной основы', featuredIntro: 'Первый структурированный набор данных с источниками и датами проверки.', deadlineTitle: 'Сроки, за которыми стоит следить', disciplines: 'Поиск по направлению', cityTitle: 'Двенадцать студенческих городов — одно путешествие', guideTitle: 'Поступление шаг за шагом' },
  universities: { title: 'Университеты', intro: 'Фильтруйте подборку по городу, региону и направлению.', searchPlaceholder: 'Поиск вуза, города или направления', noResults: 'По этим фильтрам ничего не найдено.' },
  programs: { title: 'Программы', intro: 'Сравнивайте степень, язык, длительность и статус приёма.', searchPlaceholder: 'Поиск программы или вуза', noResults: 'Программы не найдены.', degree: 'Уровень', discipline: 'Направление' },
  scholarships: { title: 'Стипендии', intro: 'Покрытие, маршруты подачи и официальные ссылки.', coverage: 'Покрытие', stipend: 'Ежемесячная выплата' },
  cities: { title: 'Студенческие города', intro: 'Расположение вузов, климат, кухня и повседневная жизнь.', climate: 'Климат', food: 'Что попробовать', sights: 'Что увидеть', universities: 'Вузы города', mapNote: 'Распределение городов показано на утверждённой стандартной карте. Метки носят справочный характер.' },
  favorites: { title: 'Ваш список', intro: 'Сохранено на этом устройстве. Сравните до четырёх программ.', empty: 'Сохранённых программ пока нет.', localOnly: 'Данные остаются в браузере и не загружаются на сервер.' },
  guide: { title: 'Гиды по поступлению', intro: 'Практические списки от выбора программы до приезда.' },
  about: { title: 'Общественный проект, основанный на источниках', intro: 'Атлас собирает разрозненную официальную информацию в понятную отправную точку.', mission: 'Зачем создан проект', missionText: 'Абитуриентам приходится сравнивать десятки страниц разного формата и давности. Проект упрощает сравнение и сохраняет прямую ссылку на официальный источник.', creator: 'Об авторе', creatorText: 'Некоммерческий информационный проект для иностранных студентов, созданный и поддерживаемый Henry Yang.', data: 'Как обновляются данные', dataText: 'Факты хранятся в файлах с историей изменений, проверяются по официальным источникам и автоматически контролируются на устаревание и битые ссылки.' },
  contact: { title: 'Связь и исправления', intro: 'Сообщите об устаревших данных, битой ссылке или предложите программу. Не отправляйте документы.', category: 'Тема', incorrect: 'Ошибка или устаревшие данные', broken: 'Битая ссылка', suggest: 'Предложить программу', other: 'Другое', message: 'Сообщение', source: 'Официальная ссылка (необязательно)', email: 'Email для ответа (необязательно)', consent: 'Я понимаю, что форма предназначена только для обратной связи, и не буду отправлять конфиденциальные документы.', submit: 'Отправить', sending: 'Отправка…', success: 'Спасибо. Сообщение отправлено конфиденциально.', error: 'Не удалось отправить сообщение. Попробуйте позже.' },
  footer: { project: 'Независимый некоммерческий гид. Приоритет всегда у официальных объявлений вузов.', creator: 'Автор Henry Yang', privacy: 'Конфиденциальность', disclaimer: 'Отказ от ответственности', dataPolicy: 'Политика данных', updates: 'Обновления' },
}

const dictionaries = { en, zh, ru } satisfies Record<LaunchLocale, typeof en>

export type Messages = typeof en

export function getMessages(locale: LaunchLocale): Messages {
  return dictionaries[locale]
}
