import { mkdirSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { pathToFileURL } from 'node:url'
import {
  validatePilotSourceManifestDirectory,
  type PilotSourceManifest,
} from '../validate-source-manifests'

type SqlValue = string | number | null

export type SourceImportArtifacts = {
  sql: string
  institutions: number
  sources: number
  enabledSources: number
  generatedAt: string
}

function sqlValue(value: SqlValue) {
  if (value === null) return 'NULL'
  if (typeof value === 'number') return String(value)
  return `'${value.replaceAll("'", "''")}'`
}

export function buildPilotSourceImport(
  records: PilotSourceManifest[],
  generatedAt = new Date().toISOString(),
): SourceImportArtifacts {
  if (Number.isNaN(Date.parse(generatedAt))) throw new Error('generatedAt must be an ISO timestamp')
  const sources = records
    .flatMap((record) => record.sources)
    .sort((left, right) => left.id.localeCompare(right.id))
  const institutionIds = [...new Set(records.map((record) => record.institutionId))].sort()
  const sourceIds = new Set<string>()
  for (const source of sources) {
    if (sourceIds.has(source.id)) throw new Error(`Duplicate source id: ${source.id}`)
    sourceIds.add(source.id)
  }

  const statements = [
    '-- Generated by scripts/ingestion/build-source-import.ts. Do not edit.',
    'PRAGMA foreign_keys = ON;',
  ]
  for (const source of sources) {
    const manifestJson = JSON.stringify(source)
    const enabled = source.enabled ? 1 : 0
    const nextFetchAt = source.enabled ? generatedAt : null
    statements.push(`
INSERT INTO ingestion_sources (
  source_id, manifest_json, enabled, next_fetch_at, created_at, updated_at
) VALUES (
  ${sqlValue(source.id)}, ${sqlValue(manifestJson)}, ${enabled},
  ${sqlValue(nextFetchAt)}, ${sqlValue(generatedAt)}, ${sqlValue(generatedAt)}
)
ON CONFLICT(source_id) DO UPDATE SET
  manifest_json = excluded.manifest_json,
  enabled = excluded.enabled,
  next_fetch_at = CASE
    WHEN ingestion_sources.manifest_json <> excluded.manifest_json
      OR ingestion_sources.enabled <> excluded.enabled
    THEN excluded.next_fetch_at
    ELSE ingestion_sources.next_fetch_at
  END,
  updated_at = CASE
    WHEN ingestion_sources.manifest_json <> excluded.manifest_json
      OR ingestion_sources.enabled <> excluded.enabled
    THEN excluded.updated_at
    ELSE ingestion_sources.updated_at
  END;`.trim())
  }

  statements.push(`
UPDATE ingestion_sources
SET enabled = 0,
    next_fetch_at = NULL,
    updated_at = ${sqlValue(generatedAt)}
WHERE json_extract(manifest_json, '$.institutionId') IN (
  ${institutionIds.map(sqlValue).join(', ')}
)
AND source_id NOT IN (
  ${[...sourceIds].sort().map(sqlValue).join(', ')}
)
AND enabled <> 0;`.trim())
  statements.push('PRAGMA optimize;')

  return {
    sql: `${statements.join('\n')}\n`,
    institutions: institutionIds.length,
    sources: sources.length,
    enabledSources: sources.filter((source) => source.enabled).length,
    generatedAt,
  }
}

function argument(name: string) {
  const index = process.argv.indexOf(name)
  return index >= 0 ? process.argv[index + 1] : undefined
}

function main() {
  const outputDirectory = resolve(argument('--output') ?? '.pipeline-build')
  const generatedAt = argument('--generated-at') ?? new Date().toISOString()
  const records = validatePilotSourceManifestDirectory()
  const artifacts = buildPilotSourceImport(records, generatedAt)
  mkdirSync(outputDirectory, { recursive: true })
  const sqlPaths = records.map((record) => {
    const sqlPath = join(outputDirectory, `${record.institutionId}.source-manifests.sql`)
    writeFileSync(sqlPath, buildPilotSourceImport([record], generatedAt).sql, 'utf8')
    return sqlPath
  })
  const manifestPath = join(outputDirectory, 'pilot-source-manifests.manifest.json')
  writeFileSync(manifestPath, JSON.stringify({
    institutions: artifacts.institutions,
    sources: artifacts.sources,
    enabledSources: artifacts.enabledSources,
    generatedAt: artifacts.generatedAt,
    sqlPaths,
  }, null, 2), 'utf8')
  process.stdout.write(`${manifestPath}\n`)
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) main()
