import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { z } from 'zod'
import { SOURCE_CATEGORIES } from '../../workers/ingestion/src/manifest-schema'
import {
  validateDoubleFirstClassRegistry,
  type DoubleFirstClassRegistry,
} from './double-first-class-registry'

const httpsUrl = z.url().refine((value) => new URL(value).protocol === 'https:', {
  message: 'official source URLs must use HTTPS',
})

const sourceSchema = z.object({
  targetId: z.string().min(1),
  institutionId: z.string().regex(/^uni-[a-z0-9-]+$/),
  institutionNameEn: z.string().min(1),
  institutionNameZh: z.string().min(2),
  region: z.string().min(1),
  province: z.string().min(1),
  sourceCategory: z.enum(SOURCE_CATEGORIES),
  officialUrl: httpsUrl,
  allowedHosts: z.array(z.string().min(1)).min(1),
  evidenceUrl: httpsUrl,
  verificationStatus: z.literal('verified_official'),
  verificationMethod: z.string().min(1),
}).strict()

export const officialSourceCohortSchema = z.object({
  format: z.literal('studyinchina.official-source-cohort'),
  formatVersion: z.literal(1),
  cohortId: z.string().min(1),
  checkedAt: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
  scope: z.object({
    regions: z.array(z.string().min(1)).min(1),
    institutionCount: z.number().int().positive(),
    sourceCount: z.number().int().positive(),
    requiredCategories: z.array(z.enum(SOURCE_CATEGORIES)).min(1),
  }).strict(),
  sources: z.array(sourceSchema).min(1),
}).strict()

export type OfficialSourceCohort = z.infer<typeof officialSourceCohortSchema>

export type OfficialSourceCohortImport = {
  sql: string
  cohorts: number
  institutions: number
  sources: number
  generatedAt: string
}

function sqlValue(value: string | number | null): string {
  if (value === null) return 'NULL'
  if (typeof value === 'number') return String(value)
  return `'${value.replaceAll("'", "''")}'`
}

function assertCohortInvariants(cohort: OfficialSourceCohort): void {
  const institutionIds = new Set(cohort.sources.map((source) => source.institutionId))
  const sourceIds = new Set(cohort.sources.map((source) => source.targetId))
  const requiredCategories = new Set(cohort.scope.requiredCategories)
  if (institutionIds.size !== cohort.scope.institutionCount) {
    throw new Error(`${cohort.cohortId}: institutionCount does not match sources`)
  }
  if (cohort.sources.length !== cohort.scope.sourceCount) {
    throw new Error(`${cohort.cohortId}: sourceCount does not match sources`)
  }
  if (sourceIds.size !== cohort.sources.length) {
    throw new Error(`${cohort.cohortId}: source targetId values must be unique`)
  }
  if (requiredCategories.size !== cohort.scope.requiredCategories.length) {
    throw new Error(`${cohort.cohortId}: requiredCategories must be unique`)
  }
  for (const source of cohort.sources) {
    const host = new URL(source.officialUrl).hostname.toLowerCase()
    if (!source.allowedHosts.map((value) => value.toLowerCase()).includes(host)) {
      throw new Error(`${source.targetId}: official URL host is not allowed`)
    }
  }
  for (const institutionId of institutionIds) {
    const categories = new Set(
      cohort.sources
        .filter((source) => source.institutionId === institutionId)
        .map((source) => source.sourceCategory),
    )
    for (const category of requiredCategories) {
      if (!categories.has(category)) {
        throw new Error(`${cohort.cohortId}: ${institutionId} is missing ${category}`)
      }
    }
  }
}

export function validateOfficialSourceCohort(value: unknown): OfficialSourceCohort {
  const cohort = officialSourceCohortSchema.parse(value)
  assertCohortInvariants(cohort)
  return cohort
}

export function loadOfficialSourceCohorts(
  directory = resolve('content/source-registry/cohorts'),
): OfficialSourceCohort[] {
  return readdirSync(directory)
    .filter((name) => name.endsWith('.official-sources.v1.json'))
    .sort()
    .map((name) => validateOfficialSourceCohort(
      JSON.parse(readFileSync(join(directory, name), 'utf8')) as unknown,
    ))
}

export function buildOfficialSourceCohortImport(
  cohorts: OfficialSourceCohort[],
  registry: DoubleFirstClassRegistry,
  generatedAt = new Date().toISOString(),
): OfficialSourceCohortImport {
  if (cohorts.length === 0) throw new Error('At least one official source cohort is required')
  if (Number.isNaN(Date.parse(generatedAt))) throw new Error('generatedAt must be an ISO timestamp')

  const targetByName = new Map(registry.targets.map((target) => [target.officialNameZh, target]))
  const institutionMappings = new Map<string, string>()
  const sourceIds = new Set<string>()
  const statements = [
    '-- Generated by scripts/ingestion/build-official-source-cohort-import.ts. Do not edit.',
    'PRAGMA foreign_keys = ON;',
  ]

  for (const cohort of cohorts) {
    assertCohortInvariants(cohort)
    const checkedAt = `${cohort.checkedAt}T00:00:00.000Z`
    for (const source of cohort.sources) {
      if (sourceIds.has(source.targetId)) throw new Error(`Duplicate source targetId: ${source.targetId}`)
      sourceIds.add(source.targetId)
      const target = targetByName.get(source.institutionNameZh)
      if (!target) throw new Error(`${source.institutionNameZh} is outside the official target registry`)
      if (target.catalogInstitutionId && target.catalogInstitutionId !== source.institutionId) {
        throw new Error(`${source.institutionNameZh} has conflicting catalog institution IDs`)
      }
      const priorTargetId = institutionMappings.get(source.institutionId)
      if (priorTargetId && priorTargetId !== target.targetId) {
        throw new Error(`${source.institutionId} maps to multiple official targets`)
      }
      institutionMappings.set(source.institutionId, target.targetId)

      const lookup = `(SELECT source_id FROM ingestion_sources
    WHERE json_extract(manifest_json, '$.institutionId') = ${sqlValue(source.institutionId)}
      AND json_extract(manifest_json, '$.officialUrl') = ${sqlValue(source.officialUrl)}
    ORDER BY source_id LIMIT 1)`
      const intervalDays = source.sourceCategory.includes('scholarship') ? 7 : 30
      const nextCheckAt = new Date(`${cohort.checkedAt}T00:00:00.000Z`)
      nextCheckAt.setUTCDate(nextCheckAt.getUTCDate() + intervalDays)
      statements.push(`UPDATE institution_targets
SET catalog_institution_id = COALESCE(catalog_institution_id, ${sqlValue(source.institutionId)}),
    onboarding_status = CASE
      WHEN onboarding_status = 'registered' THEN 'source_discovery'
      ELSE onboarding_status
    END,
    updated_at = ${sqlValue(generatedAt)}
WHERE target_id = ${sqlValue(target.targetId)};`)
      statements.push(`UPDATE institution_target_source_coverage
SET coverage_status = CASE
      WHEN coverage_status = 'parser_pending' THEN 'parser_pending'
      WHEN ${lookup} IS NOT NULL THEN 'registered'
      ELSE 'discovered'
    END,
    official_url = ${sqlValue(source.officialUrl)},
    registered_source_id = ${lookup},
    note = ${sqlValue(`Verified by ${cohort.cohortId}; evidence: ${source.evidenceUrl}`)},
    checked_at = ${sqlValue(checkedAt)},
    next_check_at = ${sqlValue(nextCheckAt.toISOString())},
    updated_at = ${sqlValue(generatedAt)}
WHERE target_id = ${sqlValue(target.targetId)}
  AND source_category = ${sqlValue(source.sourceCategory)};`)
    }
  }
  statements.push('PRAGMA optimize;')

  return {
    sql: `${statements.join('\n')}\n`,
    cohorts: cohorts.length,
    institutions: institutionMappings.size,
    sources: sourceIds.size,
    generatedAt,
  }
}

function option(name: string): string | undefined {
  const index = process.argv.indexOf(name)
  return index >= 0 ? process.argv[index + 1] : undefined
}

function runCli(): void {
  const directory = resolve(option('--directory') ?? 'content/source-registry/cohorts')
  const registryPath = resolve(
    option('--registry') ?? 'content/source-manifests/double-first-class/targets.v1.json',
  )
  const outputPath = resolve(
    option('--output') ?? '.pipeline-build/official-source-cohorts.sql',
  )
  const generatedAt = option('--generated-at') ?? new Date().toISOString()
  const registry = validateDoubleFirstClassRegistry(
    JSON.parse(readFileSync(registryPath, 'utf8')) as unknown,
  )
  const artifact = buildOfficialSourceCohortImport(
    loadOfficialSourceCohorts(directory),
    registry,
    generatedAt,
  )
  mkdirSync(dirname(outputPath), { recursive: true })
  writeFileSync(outputPath, artifact.sql, 'utf8')
  process.stdout.write(`${JSON.stringify({ outputPath, ...artifact, sql: undefined })}\n`)
}

if (resolve(process.argv[1] ?? '') === fileURLToPath(import.meta.url)) {
  try {
    runCli()
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error))
    process.exit(1)
  }
}
