import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  validateDoubleFirstClassRegistry,
  type DoubleFirstClassRegistry,
} from './double-first-class-registry'
import { SOURCE_CATEGORIES } from '../../workers/ingestion/src/manifest-schema'

type SqlValue = string | number | null

export type DoubleFirstClassTargetImport = {
  sql: string
  cohortId: string
  targets: number
  coverageRows: number
  generatedAt: string
}

function sqlValue(value: SqlValue): string {
  if (value === null) return 'NULL'
  if (typeof value === 'number') return String(value)
  return `'${value.replaceAll("'", "''")}'`
}

export function buildDoubleFirstClassTargetImport(
  registry: DoubleFirstClassRegistry,
  generatedAt = new Date().toISOString(),
): DoubleFirstClassTargetImport {
  if (Number.isNaN(Date.parse(generatedAt))) {
    throw new Error('generatedAt must be an ISO timestamp')
  }

  const cohort = registry.cohort
  const source = registry.officialSource
  const statements = [
    '-- Generated by scripts/ingestion/build-double-first-class-target-import.ts. Do not edit.',
    'PRAGMA foreign_keys = ON;',
    `INSERT INTO institution_target_cohorts (
  cohort_id, title_zh, official_page_url, official_attachment_url,
  official_institution_count, content_sha256, published_on, checked_on,
  created_at, updated_at
) VALUES (
  ${sqlValue(cohort.id)}, ${sqlValue(cohort.titleZh)},
  ${sqlValue(source.pageUrl)}, ${sqlValue(source.attachmentUrl)},
  ${cohort.officialInstitutionCount}, ${sqlValue(source.contentSha256)},
  ${sqlValue(source.publishedAt)}, ${sqlValue(source.checkedAt)},
  ${sqlValue(generatedAt)}, ${sqlValue(generatedAt)}
)
ON CONFLICT(cohort_id) DO UPDATE SET
  title_zh = excluded.title_zh,
  official_page_url = excluded.official_page_url,
  official_attachment_url = excluded.official_attachment_url,
  official_institution_count = excluded.official_institution_count,
  content_sha256 = excluded.content_sha256,
  published_on = excluded.published_on,
  checked_on = excluded.checked_on,
  updated_at = CASE
    WHEN institution_target_cohorts.title_zh <> excluded.title_zh
      OR institution_target_cohorts.official_page_url <> excluded.official_page_url
      OR institution_target_cohorts.official_attachment_url <> excluded.official_attachment_url
      OR institution_target_cohorts.official_institution_count <> excluded.official_institution_count
      OR institution_target_cohorts.content_sha256 <> excluded.content_sha256
      OR institution_target_cohorts.published_on <> excluded.published_on
      OR institution_target_cohorts.checked_on <> excluded.checked_on
    THEN excluded.updated_at
    ELSE institution_target_cohorts.updated_at
  END;`,
  ]

  for (const target of registry.targets) {
    statements.push(`INSERT INTO institution_targets (
  target_id, cohort_id, ordinal, official_name_zh, catalog_institution_id,
  onboarding_status, created_at, updated_at
) VALUES (
  ${sqlValue(target.targetId)}, ${sqlValue(cohort.id)}, ${target.ordinal},
  ${sqlValue(target.officialNameZh)}, ${sqlValue(target.catalogInstitutionId ?? null)},
  'registered', ${sqlValue(generatedAt)}, ${sqlValue(generatedAt)}
)
ON CONFLICT(target_id) DO UPDATE SET
  cohort_id = excluded.cohort_id,
  ordinal = excluded.ordinal,
  official_name_zh = excluded.official_name_zh,
  catalog_institution_id = excluded.catalog_institution_id,
  updated_at = CASE
    WHEN institution_targets.cohort_id <> excluded.cohort_id
      OR institution_targets.ordinal <> excluded.ordinal
      OR institution_targets.official_name_zh <> excluded.official_name_zh
      OR institution_targets.catalog_institution_id IS NOT excluded.catalog_institution_id
    THEN excluded.updated_at
    ELSE institution_targets.updated_at
  END;`)

    for (const sourceCategory of SOURCE_CATEGORIES) {
      statements.push(`INSERT INTO institution_target_source_coverage (
  target_id, source_category, coverage_status, created_at, updated_at
) VALUES (
  ${sqlValue(target.targetId)}, ${sqlValue(sourceCategory)}, 'discovery_pending',
  ${sqlValue(generatedAt)}, ${sqlValue(generatedAt)}
)
ON CONFLICT(target_id, source_category) DO NOTHING;`)
    }
  }

  // Count invariants are validated before generation and verified after import.
  statements.push('PRAGMA optimize;')

  return {
    sql: `${statements.join('\n')}\n`,
    cohortId: cohort.id,
    targets: registry.targets.length,
    coverageRows: registry.targets.length * SOURCE_CATEGORIES.length,
    generatedAt,
  }
}

function option(name: string): string | undefined {
  const index = process.argv.indexOf(name)
  return index >= 0 ? process.argv[index + 1] : undefined
}

function runCli(): void {
  const inputPath = resolve(
    option('--input')
      ?? 'content/source-manifests/double-first-class/targets.v1.json',
  )
  const outputPath = resolve(
    option('--output')
      ?? '.pipeline-build/double-first-class-targets.sql',
  )
  const generatedAt = option('--generated-at') ?? new Date().toISOString()
  const registry = validateDoubleFirstClassRegistry(
    JSON.parse(readFileSync(inputPath, 'utf8')) as unknown,
  )
  const artifact = buildDoubleFirstClassTargetImport(registry, generatedAt)
  mkdirSync(dirname(outputPath), { recursive: true })
  writeFileSync(outputPath, artifact.sql, 'utf8')
  process.stdout.write(
    `${JSON.stringify({
      outputPath,
      cohortId: artifact.cohortId,
      targets: artifact.targets,
      coverageRows: artifact.coverageRows,
      generatedAt: artifact.generatedAt,
    })}\n`,
  )
}

if (resolve(process.argv[1] ?? '') === fileURLToPath(import.meta.url)) {
  try {
    runCli()
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error))
    process.exit(1)
  }
}
