import { notFound } from 'next/navigation'
import { PolicyPage } from '@/components/features/PolicyPage'
import { getMessages } from '@/i18n/messages'
import { pageMetadata, requireLocale } from '@/lib/site'
export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }) { const locale = requireLocale((await params).locale) || 'en'; const m = getMessages(locale); return pageMetadata(locale, m.footer.dataPolicy, m.about.dataText, 'data-policy') }
export default async function DataPolicyPage({ params }: { params: Promise<{ locale: string }> }) { const locale = requireLocale((await params).locale); if (!locale) notFound(); const z = locale === 'zh'; const r = locale === 'ru'; return <PolicyPage locale={locale} eyebrow={z ? '可信资料方法' : r ? 'Методика данных' : 'Source-led methodology'} title={z ? '数据来源与更新政策' : r ? 'Источники и обновления' : 'Data sources and update policy'} intro={z ? '每条动态招生事实都应有来源、核验日期、复核日期和可见状态。' : r ? 'У каждого изменяемого факта должны быть источник, дата проверки, срок пересмотра и видимый статус.' : 'Every changing admissions fact should have a source, verification date, review date and visible status.'} sections={[
    { title: z ? '来源优先级' : r ? 'Приоритет источников' : 'Source hierarchy', items: [z ? '优先使用大学国际招生官网、官方申请系统和政府机构页面。' : r ? 'Приоритет — международные страницы вузов, официальные системы подачи и государственные сайты.' : 'Prefer university international-admissions pages, official application systems and government pages.', z ? '社交媒体、转载和第三方平台只用于发现线索，不能单独支持费用、截止日期或要求。' : r ? 'Соцсети, репосты и сторонние платформы — только подсказки, не доказательство сроков, цен или требований.' : 'Social media, reposts and third-party platforms are leads only; they cannot alone support fees, deadlines or requirements.'] },
    { title: z ? '状态含义' : r ? 'Статусы' : 'Status meanings', items: [z ? '已核验：已根据当前官方来源核对，可进入公开目录。' : r ? 'Проверено: сверено с актуальным официальным источником и может быть опубликовано.' : 'Verified: checked against a current official source and eligible for publication.', z ? '核验中：已录入但尚未完成发布级复核，不会进入生产页面或搜索引擎。' : r ? 'Черновик: проверка не завершена; запись не попадает на публичные страницы и в поисковые системы.' : 'Being verified: not publication-reviewed and excluded from production pages and search engines.', z ? '需要复核：已超过计划复核日期或存在冲突，可继续显示但会醒目标记。' : r ? 'Нужна проверка: срок пересмотра прошёл или есть противоречие; запись явно помечается.' : 'Needs review: past its review date or conflicting; it remains visibly marked.', z ? '已归档：历史记录仅保留在版本数据中，不作为当前申请依据。' : r ? 'Архив: запись сохраняется в истории данных, но не публикуется как актуальная.' : 'Archived: retained in versioned data history, not published as current guidance.'] },
    { title: z ? '未知与旧周期' : r ? 'Неизвестные и старые данные' : 'Unknown and previous cycles', paragraphs: [z ? '未公布字段保存为 null 并显示“尚未公布”。旧周期归档，不复制为当前日期。' : r ? 'Необъявленные значения хранятся как null. Старые циклы архивируются, а не копируются в текущий год.' : 'Unannounced values are stored as null and shown as not announced. Previous cycles are archived, never copied into a current year.'] },
    { title: z ? '更新节奏' : r ? 'График обновлений' : 'Review cadence', items: [z ? '每周自动检查外链；403、429 和超时转为人工检查。' : r ? 'Ссылки проверяются еженедельно; 403, 429 и тайм-ауты направляются на ручную проверку.' : 'Links are checked weekly; 403, 429 and timeouts become manual-review items.', z ? '每月生成数据健康清单；每年 1 月与 8–9 月全量人工复核。' : r ? 'Ежемесячно создаётся отчёт качества; полная ручная проверка — в январе и августе–сентябре.' : 'A monthly data-health issue is created; full manual reviews happen in January and August–September.', z ? '自动化只创建待办，不自动发布招生事实。' : r ? 'Автоматизация создаёт задачи, но не публикует факты о приёме.' : 'Automation creates tasks but never publishes admissions facts automatically.'] },
  ]} /> }
