import { notFound } from 'next/navigation'
import { Badge, Card, PageHero, SectionHeading } from '@/components/ui'
import { UniversityCard } from '@/components/features/RecordCards'
import { launchLocales } from '@/i18n/config'
import { getMessages } from '@/i18n/messages'
import { formatDate, localize } from '@/lib/data/format'
import { regionLabels } from '@/lib/data/labels'
import { getCityBySlug, getData } from '@/lib/data/load'
import { pageMetadata, requireLocale } from '@/lib/site'

export function generateStaticParams() { const data = getData(); return launchLocales.flatMap((locale) => data.cities.map(({ slug }) => ({ locale, slug }))) }
export async function generateMetadata({ params }: { params: Promise<{ locale: string; slug: string }> }) { const { locale: raw, slug } = await params; const locale = requireLocale(raw) || 'en'; const city = getCityBySlug(slug); if (!city) return {}; return pageMetadata(locale, localize(city.name, locale), localize(city.overview, locale), `cities/${slug}`) }
export default async function CityDetail({ params }: { params: Promise<{ locale: string; slug: string }> }) { const { locale: raw, slug } = await params; const locale = requireLocale(raw); if (!locale) notFound(); const city = getCityBySlug(slug); if (!city) notFound(); const messages = getMessages(locale); const data = getData(); const universities = data.universities.filter((item) => item.cityId === city.id); const fields = (id: string) => [...new Set(data.programs.filter((item) => item.universityId === id).map((item) => item.discipline))]; return <><PageHero variant="compact" eyebrow={`${regionLabels(locale)[city.region]} · ${localize(city.province, locale)}`} title={localize(city.name, locale)} description={localize(city.overview, locale)} meta={<><span>{universities.length} {messages.nav.universities}</span><span>{messages.common.lastVerified}: {formatDate(city.verifiedAt, locale, '—')}</span></>} /><section className="atlas-container atlas-section detail-layout"><div className="detail-main"><div className="content-grid content-grid--two"><Card accent="jade"><Badge tone="jade">{messages.cities.climate}</Badge><h2 className="atlas-card__title">{messages.cities.climate}</h2><p>{localize(city.climate, locale)}</p></Card><Card><Badge tone="gold">{messages.cities.food}</Badge><h2 className="atlas-card__title">{messages.cities.food}</h2><ul>{city.foodHighlights.map((item, index) => <li key={index}>{localize(item, locale)}</li>)}</ul></Card></div><div className="prose-panel"><h2>{messages.cities.sights}</h2><ul>{city.sights.map((item, index) => <li key={index}>{localize(item, locale)}</li>)}</ul></div><div><SectionHeading title={messages.cities.universities} level={2} /><div className="content-grid content-grid--two">{universities.map((university) => <UniversityCard key={university.id} university={university} city={city} fields={fields(university.id)} locale={locale} messages={messages} />)}</div></div></div><aside className="detail-aside"><Card><h2 className="atlas-card__title">{messages.cities.contentTitle}</h2><p className="atlas-card__description">{messages.cities.contentNotice}</p><div className="notice">{messages.common.authoritativeNotice}</div></Card></aside></section></> }
